//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.RepositoryReport.Entidades
{
    /**MODIFICIÓN*/
    public partial class rptViewAnamnesisAFEdit
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int  IdTipoParentesco { get; set; }
        public int  Edad { get; set; }
        public int  IdVivo { get; set; }
        public int  Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime  FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime  FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public int Expr1 { get; set; }
        public int Secuencia { get; set; }
        public int IdDiagnostico { get; set; }
        public string Observaciones { get; set; }
        public string CodigoDiagnostico { get; set; }
        public string CodigoPadre { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int  Expr2 { get; set; }
        public string Expr3 { get; set; }
        public System.DateTime  Expr4 { get; set; }
        public string Expr5 { get; set; }
        public System.DateTime  Expr6 { get; set; }
        public int  IdDiagnosticoPadre { get; set; }
        public int  Orden { get; set; }
        public string CadenaRecursividad { get; set; }
        public int  Nivel { get; set; }
        public string DiagnosticoSiteds { get; set; }
        public int  IndicadorPermitido { get; set; }
        public int  tipoFolder { get; set; }
        public string NombreTabla { get; set; }
        public int Persona { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public int PersonaEdad { get; set; }
        public int IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public int LineaOrdenAtencion { get; set; }
        public int TipoOrdenAtencion { get; set; }
        public int TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public int IdEstablecimientoSalud { get; set; }
        public int IdUnidadServicio { get; set; }
        public int IdPersonalSalud { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaAtencion { get; set; }
        public int IdEspecialidad { get; set; }
        public int IdTipoOrden { get; set; }
        public int estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
        public string Expr104 { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
    }
    
}
