using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoluccionSalud.RepositoryReport.Entidades
{
     public partial class rptViewAntecedentesPersonalesPatologicosGenerales_FEEdit
    {

        public int IdPatologicosGenerales { get; set; }
        public string EnfermedadesAnteriores_rb { get; set; }
        public string HipertensionSeleccion_ckb { get; set; }
        public string HipertensionTiempoenfermedad_list { get; set; }
        public string HipertensionMedicacion_rb { get; set; }
        public string HipertensionMedicacion_txt { get; set; }
        public string HipertensionTipoDiagn_list { get; set; }
        public string DiabetesSeleccion_ckb { get; set; }
        public string DiabetesTiempoenfermedad_list { get; set; }
        public string DiabetesMedicacion_rb { get; set; }
        public string DiabetesMedicacion_txt { get; set; }
        public string DiabetesTipoDiagn_list { get; set; }
        public string AsmaSeleccion_ckb { get; set; }
        public string AsmaTiempoenfermedad_list { get; set; }
        public string AsmaMedicacion_rb { get; set; }
        public string AsmaMedicacion_txt { get; set; }
        public string AsmaTipoDiagn_list { get; set; }
        public string SindromeCSeleccion_ckb { get; set; }
        public string SindromeCTiempoenfermedad_list { get; set; }
        public string SindromeCMedicacion_rb { get; set; }
        public string SindromeCMedicacion_txt { get; set; }
        public string SindromeCTipoDiagn_list { get; set; }
        public string SindromeRSeleccion_ckb { get; set; }
        public string SindromeRTiempoenfermedad_list { get; set; }
        public string SindromeRMedicacion_rb { get; set; }
        public string SindromeRMedicacion_txt { get; set; }
        public string SindromeRTipoDiagn_list { get; set; }
        public string GastritisSeleccion_ckb { get; set; }
        public string GastritisTiempoenfermedad_list { get; set; }
        public string GastritisMedicacion_rb { get; set; }
        public string GastritisMedicacion_txt { get; set; }
        public string GastritisTipoDiagn_list { get; set; }
        public string ArritmiaSeleccion_ckb { get; set; }
        public string ArritmiaTiempoenfermedad_list { get; set; }
        public string ArritmiaMedicacion_rb { get; set; }
        public string ArritmiaMedicacion_txt { get; set; }
        public string ArritmiaTipoDiagn_list { get; set; }
        public string HepatitisSeleccion_ckb { get; set; }
        public string HepatitisTiempoenfermedad_list { get; set; }
        public string HepatitisMedicacion_rb { get; set; }
        public string HepatitisMedicacion_txt { get; set; }
        public string HepatitisTipoDiagn_list { get; set; }
        public string TuberculosisSeleccion_ckb { get; set; }
        public string TuberculosisTiempoenfermedad_list { get; set; }
        public string TuberculosisMedicacion_rb { get; set; }
        public string TuberculosisMedicacion_txt { get; set; }
        public string TuberculosisTipoDiagn_list { get; set; }
        public string HipertiroidismoSeleccion_ckb { get; set; }
        public string HipertiroidismoTiempoenfermedad_list { get; set; }
        public string HipertiroidismoMedicacion_rb { get; set; }
        public string HipertiroidismoMedicacion_txt { get; set; }
        public string HipertiroidismoTipoDiagn_list { get; set; }
        public string HipotiroidismoSeleccion_ckb { get; set; }
        public string HipotiroidismoTiempoenfermedad_list { get; set; }
        public string HipotiroidismoMedicacion_rb { get; set; }
        public string HipotiroidismoMedicacion_txt { get; set; }
        public string HipotiroidismoTipoDiagn_list { get; set; }
        public string InfeccionSeleccion_ckb { get; set; }
        public string InfeccionTiempoenfermedad_list { get; set; }
        public string InfeccionMedicacion_rb { get; set; }
        public string InfeccionMedicacion_txt { get; set; }
        public string InfeccionTipoDiagn_list { get; set; }
        public string CardiopatiasSeleccion_ckb { get; set; }
        public string CardiopatiasTiempoenfermedad_list { get; set; }
        public string CardiopatiasMedicacion_rb { get; set; }
        public string CardiopatiasMedicacion_txt { get; set; }
        public string CardiopatiasTipoDiagn_list { get; set; }
        public string EtransmisionSSeleccion_ckb { get; set; }
        public string EtransmisionSTiempoenfermedad_list { get; set; }
        public string EtransmisionSMedicacion_rb { get; set; }
        public string EtransmisionSMedicacion_txt { get; set; }
        public string EtransmisionSTipoDiagn_list { get; set; }
        public string DShipoacusiaSeleccion_ckb { get; set; }
        public string DShipoacusiaTiempoenfermedad_list { get; set; }
        public string DShipoacusiaMedicacion_rb { get; set; }
        public string DShipoacusiaMedicacion_txt { get; set; }
        public string DShipoacusiaTipoDiagn_list { get; set; }
        public string DScegueraSeleccion_ckb { get; set; }
        public string DScegueraTiempoenfermedad_list { get; set; }
        public string DScegueraMedicacion_rb { get; set; }
        public string DScegueraMedicacion_txt { get; set; }
        public string DScegueraTipoDiagn_list { get; set; }
        public string DSSordoMudoSeleccion_ckb { get; set; }
        public string DSSordoMudoTiempoenfermedad_list { get; set; }
        public string DSSordoMudoMedicacion_rb { get; set; }
        public string DSSordoMudoMedicacion_txt { get; set; }
        public string DSSordoMudoTipoDiagn_list { get; set; }
        public string DSMiopiaAltaSeleccion_ckb { get; set; }
        public string DSMiopiaAltaTiempoenfermedad_list { get; set; }
        public string DSMiopiaAltaMedicacion_rb { get; set; }
        public string DSMiopiaAltaMedicacion_txt { get; set; }
        public string DSMiopiaAltaTipoDiagn_list { get; set; }
        public string CancerSeleccion_ckb { get; set; }
        public string CancerTiempoenfermedad_list { get; set; }
        public string CancerMedicacion_rb { get; set; }
        public string CancerMedicacion_txt { get; set; }
        public string CancerTipoDiagn_list { get; set; }
        public int Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int Secuencia { get; set; }
        public string OtrasEnfermedades { get; set; }
        public int IdDiagnostico { get; set; }
        public string DiagnosticoText { get; set; }
        public string TiempoEnfermedad_list { get; set; }
        public string Medicacion_txt { get; set; }
        public string TipoDiagn_list { get; set; }
        public string Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public int IDAntecedentePat { get; set; }
        public string CodigoAntecedentePat { get; set; }
        public string Descripcion { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public int PersonaEdad { get; set; }
        public int IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public int LineaOrdenAtencion { get; set; }
        public int TipoOrdenAtencion { get; set; }
        public int TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public int IdEstablecimientoSalud { get; set; }
        public int IdUnidadServicio { get; set; }
        public int IdPersonalSalud { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaAtencion { get; set; }
        public int IdEspecialidad { get; set; }
        public int IdTipoOrden { get; set; }
        public int estadoEpiAtencion { get; set; }
        public string ObservacionProximaEpiAtencion { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }

    }
}
