//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.SOA.Entidades
{
    public partial class SS_CE_TriajeAntecedentesAlergias
    {
        public decimal idalergia { get; set; }
        public Nullable<decimal> idtriaje { get; set; }
        public Nullable<decimal> idordenatencion { get; set; }
        public Nullable<decimal> idpaciente { get; set; }
        public Nullable<int> indalergiamedicamento { get; set; }
        public string alergiamedicamento1 { get; set; }
        public string alergiamedicamento2 { get; set; }
        public string alergiamedicamento3 { get; set; }
        public string alergiamedicamento4 { get; set; }
        public string alergiamedicamento5 { get; set; }
        public Nullable<int> indmedicamentoregular { get; set; }
        public string medicamentoregular1 { get; set; }
        public string medicamentoregular1dosis { get; set; }
        public string medicamentoregular1frecuencia { get; set; }
        public string medicamentoregular1via { get; set; }
        public string medicamentoregular2 { get; set; }
        public string medicamentoregular2dosis { get; set; }
        public string medicamentoregular2frecuencia { get; set; }
        public string medicamentoregular2via { get; set; }
        public string medicamentoregular3 { get; set; }
        public string medicamentoregular3dosis { get; set; }
        public string medicamentoregular3frecuencia { get; set; }
        public string medicamentoregular3via { get; set; }
        public string medicamentoregular4 { get; set; }
        public string medicamentoregular4dosis { get; set; }
        public string medicamentoregular4frecuencia { get; set; }
        public string medicamentoregular4via { get; set; }
        public string medicamentoregular5 { get; set; }
        public string medicamentoregular5dosis { get; set; }
        public string medicamentoregular5frecuencia { get; set; }
        public string medicamentoregular5via { get; set; }
        public Nullable<int> indtransfusionessanguineas { get; set; }
        public Nullable<int> indproblematransfusion { get; set; }
        public Nullable<int> indalergiaalimento { get; set; }
        public Nullable<int> indalergiacontacto { get; set; }
    }
    
}
