//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.RepositoryReport
{
    public partial class rptViewExamenTriajeFisico
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public Nullable<int> PresionMinima { get; set; }
        public Nullable<int> PresionMaxima { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<int> FrecuenciaCardiaca { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<decimal> IndiceMasaCorporal { get; set; }
        public Nullable<int> IdEstadoGeneral { get; set; }
        public Nullable<int> IdNutricion { get; set; }
        public Nullable<int> IdHidratacion { get; set; }
        public Nullable<int> IdColaboracion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Expr01 { get; set; }
        public string Expr02 { get; set; }
        public string Expr03 { get; set; }
        public string Expr04 { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
        public string Expr104 { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
    }
    
}
