//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.RepositoryReport
{
    public partial class vw_Imprimir_HC_GRILLA
    {
        public string NombreCompleto { get; set; }
        public string CodigoHC { get; set; }
        public int IdImpresion { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string UnidadReplicacion { get; set; }
        public string HostImpresion { get; set; }
        public string UsuarioImpresion { get; set; }
        public int IdPaciente { get; set; }
    }
    
}
