//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class AC_Sucursal
    {
        public string Sucursal { get; set; }
        public string SucursalGrupo { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionIngles { get; set; }
        public string CuentaContableDefecto { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string DireccionComun { get; set; }
        public string DireccionAdicional { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Compania { get; set; }
        public string CIIU { get; set; }
        public string LogoSucursal { get; set; }
        public string ACCION { get; set; }
    
        public virtual AC_SucursalGrupo AC_SucursalGrupo { get; set; }
    }
    
}
