//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class CM_CO_ListaBase
    {
        public CM_CO_ListaBase()
        {
            this.CM_CO_ListaBaseComponente = new HashSet<CM_CO_ListaBaseComponente>();
        }
    
        public int IdListaBase { get; set; }
        public string Moneda { get; set; }
        public string TipoLista { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaValidezInicio { get; set; }
        public Nullable<System.DateTime> FechaValidezFin { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IndicadorPrecioFijo { get; set; }
        public Nullable<int> IdEmpresaAnteriorUnificacion { get; set; }
        public Nullable<int> TipoPaciente { get; set; }
    
        public virtual ICollection<CM_CO_ListaBaseComponente> CM_CO_ListaBaseComponente { get; set; }
    }
    
}
