//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Web;

namespace SoluccionSalud.Entidades.Entidades
{
    [Serializable()]
    public partial class ENTITY_GLOBAL
    {
        //Agregar Flags de Exitencia Entidad Rest-Migración
        public bool FlagSaludInformePROCIngresoMantenimiento_Flag = false;
        public bool SaludInformeRutaIngresoMantenimiento_Flag = false;
        public bool OftalmologicoIngresoMantenimiento_Flag = false;
        public bool FlagSaludAnamnesisEnfermedadActual_Flag = false;
        public bool FlagSaludAnamnesisFuncionesVitales_Flag = false;
        public bool FlagSaludAnamnesisExamenClinico_Flag = false;       
        public int intentosCopiadoVisor = 0;

        public Nullable<int> ADSession { get; set; }
        public int MIRTENVIO { get; set; }
        public int MIRTHDELAY { get; set; }
        public string ACTIVOSOA { get; set; }
        public string ACTIVORULE { get; set; }
        public string CODPLATWEB { get; set; }
        public double DIASDES { get; set; }
        public Nullable<int> VistaPacienteID { get; set; }
        public Nullable<int> CapIdEscalaRamsay { get; set; }

        public static List<CuerpoHumano> listaCuerpos = new List<CuerpoHumano>();

        public static List<CW_VisorHistoria> listaresponsehc = new List<CW_VisorHistoria>();

        public static List<SS_GE_Especialidad> SESSIONlistaEspecialidad = new List<SS_GE_Especialidad>();
        
        public static List<MA_MiscelaneosDetalle> SESSIONlistaTECNOSERVICIO = new List<MA_MiscelaneosDetalle>();

        public List<SG_Agente> ListarUsuariosTotal = new List<SG_Agente>();
        public List<SS_HC_InformeAlta_FE> listaInformeAlta { get; set; }
        public Nullable<long> VistaEpisodioAtencion { get; set; }
        public Nullable<int> VistaEpisodioClinico { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public Nullable<int> EpisodioClinicoCodigo { get; set; }
        public Nullable<int> EpisodioClinico { get; set; }
        public Nullable<long> IdEpisodioAtencion { get; set; }
        public Nullable<long> EpisodioAtencion { get; set; }
        public Nullable<long> EpisodioAtencionPrim { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public string GuiaPedido { get; set; }
        public bool CheckPresseDelete { get; set; }
        public string FLAG_ANULAME { get; set; }
        public Nullable<int> EpisodioClinicoEstado { get; set; }
        public Nullable<int> APLICATIVOID { get; set; }
        public Nullable<int> INTERUPTOR { get; set; }
        public Nullable<int> INTERUPTORDELL_TEMP { get; set; }
        public Nullable<int> INTERUPTOR_TEMP { get; set; }
        public Nullable<int> FORMULARIOREGISTRO_ID { get; set; }
        public Nullable<int> PARCHE_ENFERMEDAD_ACTUAL { get; set; }
        public Nullable<int> PARCHE_ENFERMEDAD_DETALLE_ACTUAL { get; set; }
        public Nullable<int> INDICADORCOPYARDOBLE { get; set; }
        public Nullable<int> IdOrdenAtencionRelevo { get; set; }
        public int IdLineaRelevo { get; set; }
        public String NombreMedicoAntRelevo { get; set; }
        public String NombreMedicoRelevoActual { get; set; }
        public long IdPersonaMedicoRelevo { get; set; }
        public string CodigoOARelevo { get; set; }
        public Nullable<int> validarcopiarPanelCancelar { get; set; }
        public string EnfermeraNombre { get; set; }
        public Nullable<int> Enfpersonalsalud { get; set; }

        public Nullable<int> INDICA_TECNOLOGO_MIKASA { get; set; }
        public Nullable<int> EpisodioTriaje { get; set; }
        public object dataExamenMedicamentos { get; set; }
        public string FECHA_FIRMA { get; set; }
        public Nullable<int> COD_MEDICO { get; set; }
        public string NOMBRE_PROCEDIMIENTO { get; set; }
        public string NOMBRE_MEDICO { get; set; }
        public List<SS_HC_FuncionesVitales_FE> ANTENCIONESFUNCION { get; set; }
        public List<SS_HC_TriajeEmergencia_FE> ANTENCIONESFUNCIONTRIAJE { get; set; }
        public List<SS_CHE_VistaSeguridad> ListarSeguridadOpcionGlobal = new List<SS_CHE_VistaSeguridad>();

        public List<String> ListarSeguOpcionGlobalVisible = new List<String>();

        public List<String> ListarSeguOpcionPadreGlobalVisible = new List<String>();

        public int INDICA_BITACORA_FORM { get; set; }
        public string ESTADOFORMULARIO_ACCION { get; set; }
        public string ESTADOFORMULARIO_KARDEX_ACCION { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public string Sucursal { get; set; }
        public string VALIDAR_PANEL_NORT { get; set; }
        public string Establecimiento { get; set; }
        public string Compania { get; set; }
        public string UnidadReplicacion { get; set; }
        public string USUARIO { get; set; }

        public List<MA_MiscelaneosDetalle> Links = new List<MA_MiscelaneosDetalle>();

        public List<V_EpisodioAtenciones> listaCopiados = new List<V_EpisodioAtenciones>();

        public string USUARIO_GENERICO { get; set; }
        public string NOMBREUSU_GENERICO { get; set; }

        public int IDAGENTE_GENERICO { get; set; }
        public int IDEMPLEADO_GENERICO { get; set; }

        public string USUARIO_EMERG { get; set; }

        public Nullable<int> IDPERSONALSALUD_EMERG { get; set; }

        public string COD_BANDEJA { get; set; }

        public string COD_HCEBANDEJA { get; set; }

        public SS_HC_Anamnesis_AFAM_CAB_FE OBJETOS_F5 { get; set; }
        public string MODULO { get; set; }

        public int INDICA_TIPO_ORDENATENCION { get; set; }
        public int TipoOrdenAtencion { get; set; }
        public string INDICA_COD_HC { get; set; }
        public string INDICA_OA { get; set; }
        public string INDICA_COD_COMPONENTE { get; set; }

        public string MODULOBLIGATORIO { get; set; }
        public string GRUPO { get; set; }
        public string CONCEPTO { get; set; }
        public string CONCEPTODESCRIPCION { get; set; }
        public string CONCEPTODESCRIPCIONGLASGOW { get; set; }

        public Nullable<int> IDOPCION_ACTUALGLASGOW { get; set; }



        public string MENUPROCESOS { get; set; }
        public string MENURECURSOS { get; set; }
        public string DocumentoCapTriaje { get; set; }

        public string MENUREC_CODIGO { get; set; }
        public string MENUREC_DESCRIPCION { get; set; }
        public string PERFILACTUAL { get; set; }
        public int PERFILADMIN { get; set; }
        public string CODIGOPERFIL { get; set; }
        public string APPCODIGO { get; set; }
        public Nullable<int> CODPERSONA { get; set; }

        public object dataExamen { get; set; }
        public object dataInterconsulta { get; set; }
        public Object objModel { get; set; }
        public bool indicadorAuxiliar { get; set; }
        //***************  Angel  *********************//
        public Nullable<int> INDICA_FORM { get; set; }
        public Nullable<int> bitacora { get; set; }
        //***************  Angel  *********************//

        public bool indicadorUI { get; set; }
        public string OPCION_DEF { get; set; }
        public string USUARIOAGENTE_DEF { get; set; }
        public string OPCION_PADRE { get; set; }
        public string HostName { get; set; }

        public string NombreCompletoPaciente { get; set; }
        public string PacienteDatos1 { get; set; }
        public string PacienteDatos2 { get; set; }
        public string PacienteDatos3 { get; set; }

        public bool indicadorUsuario { get; set; }

        public String CodigoOrdenTriaje { get; set; }
        public Nullable<int> IDAGENTE { get; set; }
        public Nullable<int> IDAGENTEGENERICO { get; set; }
        public Nullable<int> IDAGENTE_AUDITORIA { get; set; }
        public Nullable<int> TIPOAGENTE { get; set; }

        public string TIPOAGENTEPERFILVALIDA { get; set; }

        public string TIPOTRABAJADORACTUAL { get; set; }

        public Nullable<int> IDFORMATO { get; set; }

        public Nullable<int> IDOPCION_ACTUAL { get; set; }
        public Nullable<int> IDOPCION_PADRE { get; set; }
        public Nullable<long> IDEPISODIOATENCION_TEMP { get; set; }
        public Nullable<int> EPISODIOCLINICO_TEMP { get; set; }
        public Nullable<int> ID_REFERENCIA { get; set; }
        public string UNIDREPLICACION_TEMP { get; set; }
        public Nullable<int> IDPACIENTE_TEMP { get; set; }
        public string ESTADOFORMULARIO_ACCION_TEMP { get; set; }
        public Nullable<int> INDICA_SELECCIONCRONOLOGIAS { get; set; }

        public Nullable<long> IDEPISODIOATENCION_COPY { get; set; }
        public Nullable<int> EPISODIOCLINICO_COPY { get; set; }
        public string UNIDREPLICACION_COPY { get; set; }
        public Nullable<int> IDPACIENTE_COPY { get; set; }

        public int INDICA_VISIBLE_COPY { get; set; }

        public string INDICA_NOTA_INGRESO { get; set; }
        public int INDICA_VISIBLE_IMPRESION { get; set; }

        public int INDICA_VALIDAMEDICAMENTO { get; set; }



        public int INDICA_VISIBLE_IMPRESION_TEMP { get; set; }
        public int INDICA_FORM_COMPARTIDO { get; set; }
        public string PATH_FORM_ACTUAL { get; set; }


        public string PANELCENTER_ACTUAL { get; set; }

        public string CODIGODEFORMATO_ACTUAL { get; set; }



        public string CODOPCION_PAGINA_PREVIA { get; set; }
        public string CODOPCION_PAGINA_ACTUAL { get; set; }
        public string CODOPCION_PAGINA_SGTE { get; set; }
        public string CODOPCION_ULTIMOACTOMED { get; set; }

        public string CODOPCION_GUARDADO { get; set; }
        public string URLlink { get; set; }

        public string MENSAJE_ERROR { get; set; }

        public int INDICA_VISIBLE_TB_IMPRESION { get; set; }

        public int GRUPOMEDICAMENTO { get; set; }

        public string ESTADOFORMULARIO_ACCION2 { get; set; }

        public Nullable<int> VALOR_ESPECIALIDAD { get; set; }
        public Nullable<int> IDESPECIALIDADEMER { get; set; }
        public string INDICA_TIPO_ORDENATENCION_EMER { get; set; }
        public string INDICA_ESPECIALIDAD_GRILLA { get; set; }
        public int TIPOFORMATO { get; set; }

        public Nullable<int> DETALLE_INT { get; set; }

        public string FechaReceta { get; set; }

        public string TIPOATENCION { get; set; }

        public string Password { get; set; }
        public string USUARIOESP { get; set; }

        public string CAMA { get; set; }

        public string MedicoNombre { get; set; }
        public int INDICA_RECARGAR { get; set; }
        public int OPCION_PROC_DEF { get; set; }
        public Nullable<int> IDSECUENCIA_AUX { get; set; }
        public Nullable<int> IDDEVOLUCIONPRODUCTO { get; set; }
        public Nullable<int> IDSOLICITUDMED { get; set; }

        public Nullable<int> INDICADOR_DOACEPTAR { get; set; }

        public Nullable<int> IDFAVORITO { get; set; }
        public Nullable<int> TIENE_FAVORITOS { get; set; }
        public int OPCION_STOCK_DEF { get; set; }
        public virtual PERSONAMAST PERSONAMAST { get; set; }

        public Nullable<long> EpisodioAtencionBeta { get; set; }
        public Nullable<long> EpisodioAtencionBeta2 { get; set; }

        public string CodeForm { get; set; }
        public Nullable<int> DinamicSecuencia { get; set; }

        public string tipopaciente { get; set; }

        public Nullable<int> IdMedico { get; set; }


        public string RUTA_ARCHIVOS { get; set; }

        public Nullable<decimal> BalanceAcumulado { get; set; }

        public Nullable<int> MODALIDAD_TEMP { get; set; }

        public int INDICA_VISIBLE_OBLIGATORIO { get; set; }
        public int INDICA_ESTADO_DG { get; set; }
        public int INDICA_INFORME_ALTA { get; set; }
        public int IdMedicoaudi { get; set; }
        public int INDICADOR_HOSPI { get; set; }
        public string INDICADOR_EMER { get; set; }
        public object INDICADOR_COMBO { get; set; }

        public object Session_TIPOVIA { get; set; }
        public object Session_UNITIEMPO { get; set; }
        public object Session_TIPOREGMED { get; set; }
        public object Session_INDIRECETA { get; set; }

        public int ValorServicioTecno { get; set; }
        public string SECUENCIAL_HCE { get; set; }
        public int INDICADOR_INTERCONSULTA { get; set; }
        public int CONTADOR_BORRAR_SESION_CABECERA { get; set; }

        public String IndicaBorrarSesionTriaje { get; set; }

        public String ACCCION_ABRIR_ARBOL { get; set; }
        public int ContadorTriaje { get; set; }

        public string INDICADORSERVICIOALTA { get; set; }
        public string CodigoHceRequest { get; set; }

        public string CODIGOOADISPENSACION { get; set; }

      //  public Nullable<DateTime> FECHABANDEJADISPENSACION { get; set; }
        public  DateTime FECHABANDEJADISPENSACION { get; set; }

        public int FLAT_INTERCONSULTA { get; set; }

        public bool alergiaExiste { get; set; }

        public bool despachoExtra { get; set; }

        public string flagFav { get; set; }

        public static ENTITY_GLOBAL Instance
        {
            get
            {
                ENTITY_GLOBAL obj = (ENTITY_GLOBAL)HttpContext.Current.Session["ENTITY_GLOBAL"];
                return obj;
            }
        }

        public int IdPersonResponse { get; set; }

        public string ListadoOrigen { get; set; }

        public static void ReplaceGlobal(ENTITY_GLOBAL NewInstance)
        {

            HttpContext.Current.Session.Remove("ENTITY_GLOBAL");
            HttpContext.Current.Session.Add("ENTITY_GLOBAL", NewInstance);
        }

        //copiado


        public string COPIADO_DISABLED { get; set; }
        public int TipoCopiado { get; set; }
        public string IdOrdenAtecionCopiado { get; set; }
        public string LineaCopiado { get; set; }
        public Nullable<long> IdEpisodioAtencionCopiado { get; set; }
        public int EpisodioClinicoCopiado { get; set; }
        public string UnidadReplicacionCopiado { get; set; }

        public List<MA_MiscelaneosDetalle> listaparchesito = new List<MA_MiscelaneosDetalle>();


    }


}
