//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class MA_MiscelaneosDetalle
    {
        public string AplicacionCodigo { get; set; }
        public string CodigoTabla { get; set; }
        public string Compania { get; set; }
        public string CodigoElemento { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<double> ValorNumerico { get; set; }
        public string ValorCodigo1 { get; set; }
        public string ValorCodigo2 { get; set; }
        public string ValorCodigo3 { get; set; }
        public string ValorCodigo4 { get; set; }
        public string ValorCodigo5 { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public byte[] Timestamp { get; set; }
        public string ACCION { get; set; }
        public Nullable<int> RowID { get; set; }
        public Nullable<int> ValorEntero1 { get; set; }
        public Nullable<int> ValorEntero2 { get; set; }
        public Nullable<int> ValorEntero3 { get; set; }
        public Nullable<int> ValorEntero4 { get; set; }
        public Nullable<int> ValorEntero5 { get; set; }
        public string ValorCodigo6 { get; set; }
        public string ValorCodigo7 { get; set; }
        public Nullable<int> ValorEntero6 { get; set; }
        public Nullable<int> ValorEntero7 { get; set; }

        public string UsuarioActual { get; set; }
    
        public virtual MA_MiscelaneosHeader MA_MiscelaneosHeader { get; set; }
    }
    
}
