//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewOftalmologia_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string AVscODerecho { get; set; }
        public string AVscOIzquierdo { get; set; }
        public string AVccODerecho { get; set; }
        public string AVccOIzquierdo { get; set; }
        public string PinHoldODerecho { get; set; }
        public string PinHoldOIzquierdo { get; set; }
        public string CercaODerecho { get; set; }
        public string CercaOIzquierdo { get; set; }
        public string RefraODerechoEsfera { get; set; }
        public string RefraODerechoCilindro { get; set; }
        public string RefraODerechoEje { get; set; }
        public string ScicloPejiaOIzqEsfera { get; set; }
        public string ScicloPejiaOIzqCilindro { get; set; }
        public string ScicloPejiaOIzqEje { get; set; }
        public string RefracODerechoAV { get; set; }
        public string RefracODerechoADD { get; set; }
        public string RefracODerechoDIP { get; set; }
        public string CciclopejiaOIzqAV { get; set; }
        public string CciclopejiaOIzqADD { get; set; }
        public string CciclopejiaOIzqDIP { get; set; }
        public string Adicion { get; set; }
        public string DistanciaPupilar { get; set; }
        public string TonShiotz { get; set; }
        public string TonAplanacion { get; set; }
        public string TonOtra { get; set; }
        public string TonODerecho { get; set; }
        public string TonOIzquierdo { get; set; }
        public string PaquimetriaODerecho { get; set; }
        public string PaquimetriaOIzquierdo { get; set; }
        public string CorreccionODerecho { get; set; }
        public string CorreccionOIzquierdo { get; set; }
        public string Parpados_anexos { get; set; }
        public string Cornea_Cristalino_Esclera { get; set; }
        public string Iris_Pupila { get; set; }
        public string FondOjo_GoniosCopia { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public string estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
        public string Expr104 { get; set; }
    }
    
}
