//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewTriajeEmergencia_FE
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioTriaje { get; set; }
        public int IdFuncionVital { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> PresionArterialMSD1 { get; set; }
        public Nullable<int> PresionArterialMSD2 { get; set; }
        public Nullable<int> PresionArterialMSI { get; set; }
        public Nullable<int> PresionArterialMS2 { get; set; }
        public Nullable<decimal> FrecuenciaCardiaca { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<int> SaturacionOxigeno { get; set; }
        public Nullable<int> FrecuenciaCardFetal_Flag { get; set; }
        public Nullable<int> FrecuenciaCard_FetalAdd { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> TiempoEnfermedad { get; set; }
        public string TiempoEnfermedadUnidad { get; set; }
        public string Motivodeingreso { get; set; }
        public string Sintomas { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public int IdEpisodioTriaje { get; set; }
        public string CodigoOT { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<int> FlagFirma { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public Nullable<int> IdMedicoFirma { get; set; }
        public string ObservacionFirma { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
        public string estadoEpiAtencion { get; set; }
        public int Especialidad { get; set; }
    }
    
}
