//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewKardex3
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int Secuencia { get; set; }
        public int IdMedicacion { get; set; }
        public string Medicacion { get; set; }
        public string Dosis { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<decimal> DiasTratamiento { get; set; }
        public Nullable<decimal> DiaTratamiento { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraAdministracion { get; set; }
        public Nullable<int> Hora0 { get; set; }
        public Nullable<int> Hora1 { get; set; }
        public Nullable<int> Hora2 { get; set; }
        public Nullable<int> Hora3 { get; set; }
        public Nullable<int> Hora4 { get; set; }
        public Nullable<int> Hora5 { get; set; }
        public Nullable<int> Hora6 { get; set; }
        public Nullable<int> Hora7 { get; set; }
        public Nullable<int> Hora8 { get; set; }
        public Nullable<int> Hora9 { get; set; }
        public Nullable<int> Hora10 { get; set; }
        public Nullable<int> Hora11 { get; set; }
        public Nullable<int> Hora12 { get; set; }
        public Nullable<int> Hora13 { get; set; }
        public Nullable<int> Hora14 { get; set; }
        public Nullable<int> Hora15 { get; set; }
        public Nullable<int> Hora16 { get; set; }
        public Nullable<int> Hora17 { get; set; }
        public Nullable<int> Hora18 { get; set; }
        public Nullable<int> Hora19 { get; set; }
        public Nullable<int> Hora20 { get; set; }
        public Nullable<int> Hora21 { get; set; }
        public Nullable<int> Hora22 { get; set; }
        public Nullable<int> Hora23 { get; set; }
        public string Accion { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string ObservacionProximaEpiAtencion { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
    }
    
}
