//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewCabezeraAntecedenAlergias_FE
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioTriaje { get; set; }
        public Nullable<int> IdFormaInicio { get; set; }
        public Nullable<int> IdCursoEnfermedad { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string TieneHistoria { get; set; }
        public string TieneAlimento { get; set; }
        public string TieneAmbiental { get; set; }
        public string TieneContacto { get; set; }
        public string MedicamentoRegular { get; set; }
        public string TransfusionSanguinea { get; set; }
        public string ProblemaTransfusion { get; set; }
        public string Comentarios { get; set; }
        public string IdMedicamento { get; set; }
        public Nullable<int> IdTipoAlergiaDet { get; set; }
        public string LineaDet { get; set; }
        public string FamiliaDet { get; set; }
        public string SubFamiliaDet { get; set; }
        public string DesdeCuandoDet { get; set; }
        public string ObservacionesDet { get; set; }
        public Nullable<int> EstudioAlegistaDet { get; set; }
        public string TipoRegistroDet { get; set; }
        public string DescripcionManualDet { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public string idordenatencion { get; set; }
        public string CodigoOT { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidadPac { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr103 { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
    }
    
}
