//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewValoracionSocioFamAM_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string SituacionSocial { get; set; }
        public string SituacionEconomica { get; set; }
        public string Vivienda { get; set; }
        public string RelacionesSociales { get; set; }
        public string ApoyoRedSocial { get; set; }
        public string Valoracion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string SS1 { get; set; }
        public string SS2 { get; set; }
        public string SS3 { get; set; }
        public string SS4 { get; set; }
        public string SS5 { get; set; }
        public string SE1 { get; set; }
        public string SE2 { get; set; }
        public string SE3 { get; set; }
        public string SE4 { get; set; }
        public string SE5 { get; set; }
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string RS1 { get; set; }
        public string RS2 { get; set; }
        public string RS3 { get; set; }
        public string RS4 { get; set; }
        public string RS5 { get; set; }
        public string ARS1 { get; set; }
        public string ARS2 { get; set; }
        public string ARS3 { get; set; }
        public string ARS4 { get; set; }
        public string ARS5 { get; set; }
    }
    
}
