//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewFichaAnestesia_3_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> VisualizacionaAnestesia { get; set; }
        public Nullable<int> MonitorizacionAnestesia { get; set; }
        public Nullable<decimal> PresionArterial15_1 { get; set; }
        public Nullable<decimal> PresionArterial15_2 { get; set; }
        public Nullable<decimal> PresionArterial30_1 { get; set; }
        public Nullable<decimal> PresionArterial30_2 { get; set; }
        public Nullable<decimal> PresionArterial45_1 { get; set; }
        public Nullable<decimal> PresionArterial45_2 { get; set; }
        public Nullable<decimal> PresionArterial60_1 { get; set; }
        public Nullable<decimal> PresionArterial60_2 { get; set; }
        public string AnestesiaEKG15 { get; set; }
        public string AnestesiaEKG30 { get; set; }
        public string AnestesiaEKG45 { get; set; }
        public string AnestesiaEKG60 { get; set; }
        public Nullable<decimal> PresionS0215 { get; set; }
        public Nullable<decimal> PresionS0230 { get; set; }
        public Nullable<decimal> PresionS0245 { get; set; }
        public Nullable<decimal> PresionS0260 { get; set; }
        public Nullable<decimal> PresionETC0215 { get; set; }
        public Nullable<decimal> PresionETC0230 { get; set; }
        public Nullable<decimal> PresionETC0245 { get; set; }
        public Nullable<decimal> PresionETC0260 { get; set; }
        public Nullable<decimal> PresionT15 { get; set; }
        public Nullable<decimal> PresionT30 { get; set; }
        public Nullable<decimal> PresionT45 { get; set; }
        public Nullable<decimal> PresionT60 { get; set; }
        public string PresionPAN15 { get; set; }
        public string PresionPAN30 { get; set; }
        public string PresionPAN45 { get; set; }
        public string PresionPAN60 { get; set; }
        public string PresionPANI15 { get; set; }
        public string PresionPANI30 { get; set; }
        public string PresionPANI45 { get; set; }
        public string PresionPANI60 { get; set; }
        public string PresionPVC15 { get; set; }
        public string PresionPVC30 { get; set; }
        public string PresionPVC45 { get; set; }
        public string PresionPVC60 { get; set; }
        public string PresionBIS15 { get; set; }
        public string PresionBIS30 { get; set; }
        public string PresionBIS45 { get; set; }
        public string PresionBIS60 { get; set; }
        public string PresionRespiEspontanea15 { get; set; }
        public string PresionRespiEspontanea30 { get; set; }
        public string PresionRespiEspontanea45 { get; set; }
        public string PresionRespiEspontanea60 { get; set; }
        public string PresionRespiAsistida15 { get; set; }
        public string PresionRespiAsistida30 { get; set; }
        public string PresionRespiAsistida45 { get; set; }
        public string PresionRespiAsistida60 { get; set; }
        public string PresionRespiControlado15 { get; set; }
        public string PresionRespiControlado30 { get; set; }
        public string PresionRespiControlado45 { get; set; }
        public string PresionRespiControlado60 { get; set; }
        public string AGASodio15 { get; set; }
        public string AGASodio30 { get; set; }
        public string AGASodio45 { get; set; }
        public string AGASodio60 { get; set; }
        public string AGAPotasio15 { get; set; }
        public string AGAPotasio30 { get; set; }
        public string AGAPotasio45 { get; set; }
        public string AGAPotasio60 { get; set; }
        public string AGABicarbonato15 { get; set; }
        public string AGABicarbonato30 { get; set; }
        public string AGABicarbonato45 { get; set; }
        public string AGABicarbonato60 { get; set; }
        public string AGABh15 { get; set; }
        public string AGABh30 { get; set; }
        public string AGABh45 { get; set; }
        public string AGABh60 { get; set; }
        public string AGAFiO15 { get; set; }
        public string AGAFiO30 { get; set; }
        public string AGAFiO45 { get; set; }
        public string AGAFiO60 { get; set; }
        public string AGAHemoglobina15 { get; set; }
        public string AGAHemoglobina30 { get; set; }
        public string AGAHemoglobina45 { get; set; }
        public string AGAHemoglobina60 { get; set; }
        public string AGAHematogrito15 { get; set; }
        public string AGAHematogrito30 { get; set; }
        public string AGAHematogrito45 { get; set; }
        public string AGAHematogrito60 { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencionPac { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidadPac { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
        public string Expr104 { get; set; }
    }
    
}
