//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewResumenParto_FE
    {
        public string Accion { get; set; }
        public Nullable<int> Controladora { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> Fecha_Ing { get; set; }
        public string Hora_Ing { get; set; }
        public string Horas_memb { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<int> IdResParto { get; set; }
        public Nullable<int> Membranas { get; set; }
        public string Observaciones1_S { get; set; }
        public string Observaciones2_S { get; set; }
        public string P_Dur_Parto { get; set; }
        public string P_Observacion { get; set; }
        public Nullable<int> P_Selector1 { get; set; }
        public Nullable<int> P_Selector2 { get; set; }
        public Nullable<int> S_Desgarro { get; set; }
        public string S_Dur_Parto { get; set; }
        public Nullable<int> S_Episiotomia { get; set; }
        public Nullable<System.DateTime> S_Fecha_Parto { get; set; }
        public string S_Hora_Parto { get; set; }
        public Nullable<int> S_Selector1 { get; set; }
        public Nullable<int> S_Selector2 { get; set; }
        public Nullable<int> S_Selector3 { get; set; }
        public Nullable<int> S_Selector4 { get; set; }
        public string UnidadReplicacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string Version { get; set; }
        public string AU { get; set; }
        public string EG { get; set; }
        public string EGXFUR { get; set; }
        public Nullable<System.DateTime> FPP { get; set; }
        public Nullable<System.DateTime> FUR { get; set; }
        public string PFGECO { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string ObservacionProximaEpiAtencion { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
    }
    
}
