//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewInformeAlta_DatosGenerales_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdMedico { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoAlta { get; set; }
        public Nullable<int> IdPronostico { get; set; }
        public string Procedimientos { get; set; }
        public string indigenerales { get; set; }
        public string actividafisica { get; set; }
        public string indidieta { get; set; }
        public string restricciones { get; set; }
        public Nullable<System.DateTime> proximacitas { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string TipoAlta { get; set; }
        public string Pronostico { get; set; }
        public string DianosticoIngreso { get; set; }
        public string DianosticoAlta { get; set; }
        public string DianosticoApoyoDiag { get; set; }
    }
    
}
