//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewTriajeAlergias_FE
    {
        public Nullable<int> Secuencia { get; set; }
        public Nullable<int> IdTipoAlergia { get; set; }
        public string Nombre { get; set; }
        public string DesdeCuando { get; set; }
        public Nullable<int> EstudioAlegista { get; set; }
        public string Observaciones { get; set; }
        public string DescripcionManual { get; set; }
        public Nullable<int> Dosis { get; set; }
        public string via { get; set; }
        public string Frecuencia { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioTriaje { get; set; }
        public string TipoAlergiaDesc { get; set; }
        public string SI { get; set; }
        public string NO { get; set; }
        public string EstudioAlergista { get; set; }
        public string Accion { get; set; }
    }
    
}
