//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewExamenApoyoDiagnostico_FE
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int Secuencia { get; set; }
        public string Resumen { get; set; }
        public string Motivo { get; set; }
        public string TipoExamen { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> IdProcedimientoCab { get; set; }
        public Nullable<System.DateTime> FechaSolitadaCab { get; set; }
        public Nullable<int> CantidadCab { get; set; }
        public string ObservacionCab { get; set; }
        public Nullable<int> IndicadorEPSCab { get; set; }
        public string TipoCodigoCab { get; set; }
        public string CodigoSegusCab { get; set; }
        public string CodigoComponenteCab { get; set; }
        public Nullable<int> IdEspecialidadCab { get; set; }
        public Nullable<int> SecuenciaCab { get; set; }
        public string EspecificacionesCab { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string Examen { get; set; }
        public Nullable<System.DateTime> FechaSolicitada { get; set; }
        public string CodigoComponente { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> IndicadorEPS { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string TipoCodigo { get; set; }
        public string CodigoSegus { get; set; }
        public string Especificaciones { get; set; }
        public string Diagnostico { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencionPac { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidadPac { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string Expr101 { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
        public string PersMedicoNombreCompleto { get; set; }
        public string PersMedicoNombreDocumento { get; set; }
        public string EspecialidadCodigo { get; set; }
        public string EspecialidadDesc { get; set; }
        public string Expr104 { get; set; }
    }
    
}
