//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewFichaAnestesia5
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> GasasCompletas { get; set; }
        public Nullable<int> GasasIncompletas { get; set; }
        public Nullable<int> Respuesta1 { get; set; }
        public Nullable<int> Respuesta2 { get; set; }
        public Nullable<int> Respuesta3 { get; set; }
        public string Paciente_Dev_Otros { get; set; }
        public string Paciente_Prov_Otros { get; set; }
        public string Accion { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string Busqueda { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> PersonaEdad { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string ObservacionProximaEpiAtencion { get; set; }
        public string TipoAtencionDesc { get; set; }
        public string TipoTrabajadorDesc { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string EstablecimientoDesc { get; set; }
        public string UnidadServicioCodigo { get; set; }
        public string UnidadServicioDesc { get; set; }
    }
    
}
