//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewReferencia_FE
    {
        public int EpisodioClinico { get; set; }
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public string NroReferencia { get; set; }
        public string P_UNO { get; set; }
        public string P_DOS { get; set; }
        public string P_TRES { get; set; }
        public string P_CUATRO { get; set; }
        public string EstablecimientoOri { get; set; }
        public string ServicioOri { get; set; }
        public string EstablecimientoDest { get; set; }
        public string ServicioDest { get; set; }
        public string IdentificacionUsu { get; set; }
        public string Anamnesis { get; set; }
        public string EstadoGeneral { get; set; }
        public string Glasgow { get; set; }
        public string FV_T { get; set; }
        public string FV_PA { get; set; }
        public string FV_FR { get; set; }
        public string FV_FC { get; set; }
        public string Exam_aux { get; set; }
        public string Motivo { get; set; }
        public string DR_EMERGENCIA { get; set; }
        public string DR_CONSULTA_EXTERNA { get; set; }
        public string DR_HOSPITALIZACION { get; set; }
        public string FechaReferencia { get; set; }
        public string HoraReferencia { get; set; }
        public string PersonaAtiende { get; set; }
        public string CS_ESTABLE { get; set; }
        public string CS_INESTABLE { get; set; }
        public string MedicoSanna { get; set; }
        public string MedicoAtencion { get; set; }
        public string Respon_ref { get; set; }
        public string Colegiatura_ref { get; set; }
        public string Respon_serv { get; set; }
        public string Colegiatura_ser { get; set; }
        public string Respon_acomp { get; set; }
        public string Colegiatura_acomp { get; set; }
        public string Respon_recibe { get; set; }
        public string Colegiatura_recib { get; set; }
        public string CLL_ESTABLE { get; set; }
        public string CLL_INESTABLE { get; set; }
        public string CLL_FALLECIDO { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string P_CINCO { get; set; }
        public string Tratam { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencionPac { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistroPac { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdEspecialidadPac { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> estadoEpiAtencion { get; set; }
        public string Accion { get; set; }
        public string Expr102 { get; set; }
        public string Expr103 { get; set; }
    }
    
}
