//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptViewValoracionMentalAM_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> Cualfecha { get; set; }
        public Nullable<int> QueDiasemana { get; set; }
        public Nullable<int> EnquelugarEstamos { get; set; }
        public Nullable<int> CualNumerotelefono { get; set; }
        public Nullable<int> CuantosAniostiene { get; set; }
        public Nullable<int> DondeNacio { get; set; }
        public Nullable<int> NombrePresidente { get; set; }
        public Nullable<int> NombrePresidenteAnterior { get; set; }
        public Nullable<int> ApellidoMadre { get; set; }
        public Nullable<int> Restar { get; set; }
        public string ValorCognitiva { get; set; }
        public Nullable<int> Satisfecho { get; set; }
        public Nullable<int> Impotente { get; set; }
        public Nullable<int> Memoria { get; set; }
        public Nullable<int> desgano { get; set; }
        public string EstadoAfectivo { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string SatisfechoDes { get; set; }
        public string ImpotenteDes { get; set; }
        public string MemoriaDes { get; set; }
        public string DesganoDes { get; set; }
    }
    
}
