//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class rptView_ValoracionFuncionalAM_FE
    {
        public string Unidadreplicacion { get; set; }
        public long idEpisodioAtencion { get; set; }
        public int Idpaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string LD { get; set; }
        public string LI { get; set; }
        public string VD { get; set; }
        public string VI { get; set; }
        public string SHD { get; set; }
        public string SHI { get; set; }
        public string MD { get; set; }
        public string MI { get; set; }
        public string CD { get; set; }
        public string CI { get; set; }
        public string AD { get; set; }
        public string AI { get; set; }
        public string DiagnosticoFuncional { get; set; }
        public Nullable<int> estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string version { get; set; }
    }
    
}
