//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SEGURIDADGRUPO
    {
        public SEGURIDADGRUPO()
        {
            this.SEGURIDADAUTORIZACIONES = new HashSet<SEGURIDADAUTORIZACIONE>();
            this.SEGURIDADAUTORIZACIONES1 = new HashSet<SEGURIDADAUTORIZACIONE>();
            this.SEGURIDADCONCEPTOes = new HashSet<SEGURIDADCONCEPTO>();
        }
    
        public string APLICACIONCODIGO { get; set; }
        public string GRUPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ULTIMOUSUARIO { get; set; }
        public Nullable<System.DateTime> ULTIMAFECHAMODIF { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> SETCOLUMMENU { get; set; }
        public Nullable<int> SETFILAMENU { get; set; }
        public string ACCION { get; set; }
    
        public virtual ICollection<SEGURIDADAUTORIZACIONE> SEGURIDADAUTORIZACIONES { get; set; }
        public virtual ICollection<SEGURIDADAUTORIZACIONE> SEGURIDADAUTORIZACIONES1 { get; set; }
        public virtual ICollection<SEGURIDADCONCEPTO> SEGURIDADCONCEPTOes { get; set; }
    }
    
}
