//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SG_Agente
    {
        public SG_Agente()
        {
            this.SG_PerfilUsuario = new HashSet<SG_PerfilUsuario>();
            this.SS_HC_Favorito = new HashSet<SS_HC_Favorito>();
            this.SG_AgenteOpcion = new HashSet<SG_AgenteOpcion>();
        }

        public int? FlagSuper { get; set; }

        public int IdAgente { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdOrganizacion { get; set; }
        public Nullable<int> TipoAgente { get; set; }
        public string CodigoAgente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IndicadorMultiple { get; set; }
        public string Clave { get; set; }
        public Nullable<int> ExpiraClave { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdGrupoTransaccion { get; set; }
        public Nullable<int> TipoTransaccion { get; set; }
        public Nullable<int> IdOpcionDefecto { get; set; }
        public string ACCION { get; set; }
        public string Plataforma { get; set; }
        public string tipotrabajador { get; set; }
        public Nullable<int> IdCodigo { get; set; }
        public Nullable<int> Almacen { get; set; }
        public Nullable<int> flatUsuGenerico { get; set; }
        public Nullable<int> FlatAgente { get; set; }
    
        public virtual ICollection<SG_PerfilUsuario> SG_PerfilUsuario { get; set; }
        public virtual SG_Grupo SG_Grupo { get; set; }
        public virtual ICollection<SS_HC_Favorito> SS_HC_Favorito { get; set; }
        public virtual ICollection<SG_AgenteOpcion> SG_AgenteOpcion { get; set; }
    }
    
}
