//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SG_Grupo
    {
        public SG_Grupo()
        {
            this.SG_Grupo1 = new HashSet<SG_Grupo>();
            this.SG_Agente = new HashSet<SG_Agente>();
        }
    
        public int IdGrupo { get; set; }
        public Nullable<int> IdGrupoPadre { get; set; }
        public string CodigoGrupo { get; set; }
        public string CadenaRecursividad { get; set; }
        public Nullable<int> NivelGrupo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ACCION { get; set; }
    
        public virtual ICollection<SG_Grupo> SG_Grupo1 { get; set; }
        public virtual SG_Grupo SG_Grupo2 { get; set; }
        public virtual ICollection<SG_Agente> SG_Agente { get; set; }
    }
    
}
