//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_GE_ComponentePrestacion
    {
        public string Componente { get; set; }
        public string CodigoSegus { get; set; }
        public string CodigoNuevo { get; set; }
        public Nullable<int> UnidadMedida { get; set; }
        public Nullable<decimal> ValorMedida { get; set; }
        public Nullable<decimal> CantidadAsistentes { get; set; }
        public Nullable<int> Instrumentistas { get; set; }
        public Nullable<decimal> DiasHospitalizacion { get; set; }
        public Nullable<int> IndicadorImpuesto { get; set; }
        public Nullable<int> IndicadorReemplazo { get; set; }
        public Nullable<int> IndicadorEps { get; set; }
        public Nullable<int> IndicadorCita { get; set; }
        public string CentroCosto { get; set; }
        public Nullable<int> FormularioInforme { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> FormularioInformeAnastesiologo { get; set; }
        public Nullable<int> TipoPrestacion { get; set; }
        public Nullable<decimal> TiempoEjecucionExamen { get; set; }
        public Nullable<int> IndicadorHC { get; set; }
        public Nullable<int> IndicadorConsentimiento { get; set; }
        public Nullable<int> IdAreaLaboratorio { get; set; }
        public Nullable<int> IndicadorBS { get; set; }
        public Nullable<int> IndicadorAfectoEmergencia { get; set; }
        public Nullable<int> IndicadorEmergenciaMultiple { get; set; }
        public Nullable<int> IndicadorPrecioManual { get; set; }
        public string CodigoGrupo { get; set; }
        public Nullable<int> IndicadorIncluyeConsulta { get; set; }
        public Nullable<int> IndicadorPrestacionPrincipal { get; set; }
        public Nullable<int> IndicadorRequierePersonal { get; set; }
        public Nullable<int> IndicadorPaquete { get; set; }
        public Nullable<int> ClasificacionComponente { get; set; }
        public Nullable<int> EstadoBkPrecisa { get; set; }
        public int IndicadorPreQuirurgico { get; set; }
        public Nullable<int> IndicadorPaquetePart { get; set; }
    }
    
}
