//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_SeccionFormato
    {
        public SS_HC_SeccionFormato()
        {
            this.SS_HC_FormatoCampo = new HashSet<SS_HC_FormatoCampo>();
        }
    
        public int IdSeccionFormato { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public string TipoSeccion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<SS_HC_FormatoCampo> SS_HC_FormatoCampo { get; set; }
    }
    
}
