//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Ficha_Anestesia_2_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> Respuesta1Chk { get; set; }
        public Nullable<int> Respuesta2Chk { get; set; }
        public Nullable<int> Respuesta3Chk { get; set; }
        public Nullable<int> Respuesta4Chk { get; set; }
        public Nullable<int> Respuesta5Chk { get; set; }
        public Nullable<int> Respuesta6Chk { get; set; }
        public Nullable<int> Respuesta7Rdb { get; set; }
        public Nullable<int> Respuesta9Chk { get; set; }
        public Nullable<int> Respuesta10Chk { get; set; }
        public Nullable<int> Respuesta11Chk { get; set; }
        public Nullable<int> Respuesta12Chk { get; set; }
        public Nullable<int> Respuesta13Chk { get; set; }
        public Nullable<int> Respuesta14Chk { get; set; }
        public Nullable<int> Respuesta15Chk { get; set; }
        public Nullable<int> Respuesta16Chk { get; set; }
        public Nullable<int> Respuesta17Chk { get; set; }
        public Nullable<int> Respuesta18Chk { get; set; }
        public Nullable<int> Respuesta19Chk { get; set; }
        public Nullable<int> Respuesta20Chk { get; set; }
        public Nullable<int> Respuesta21Chk { get; set; }
        public Nullable<int> TET_num { get; set; }
        public Nullable<int> Facial_num { get; set; }
        public Nullable<int> Laringea_num { get; set; }
        public Nullable<int> Respuesta22Chk { get; set; }
        public Nullable<int> Respuesta23Chk { get; set; }
        public Nullable<int> Respuesta24Chk { get; set; }
        public Nullable<int> Respuesta25Chk { get; set; }
        public Nullable<int> Respuesta26Chk { get; set; }
        public Nullable<int> Respuesta28Chk { get; set; }
        public Nullable<int> Respuesta29Chk { get; set; }
        public Nullable<int> Respuesta30Chk { get; set; }
        public Nullable<int> Respuesta31Chk { get; set; }
        public Nullable<int> Respuesta32Chk { get; set; }
        public Nullable<int> Respuesta33Chk { get; set; }
        public Nullable<decimal> CATVenoso_num { get; set; }
        public Nullable<decimal> PVCCat_num { get; set; }
        public Nullable<int> Respuesta34Chk { get; set; }
        public Nullable<int> Respuesta35Chk { get; set; }
        public Nullable<int> Respuesta36Chk { get; set; }
        public Nullable<int> Respuesta37Chk { get; set; }
        public Nullable<int> Respuesta38Chk { get; set; }
        public Nullable<int> Respuesta39Chk { get; set; }
        public Nullable<int> Respuesta40Chk { get; set; }
        public Nullable<int> Respuesta41Chk { get; set; }
        public Nullable<int> Respuesta42Chk { get; set; }
        public Nullable<int> Respuesta43Chk { get; set; }
        public string Otros { get; set; }
        public Nullable<System.DateTime> Fec_Ini_Anestesia { get; set; }
        public Nullable<System.DateTime> Fec_Ini_Cirugia { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Anestesia { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Cirugia { get; set; }
        public Nullable<int> Respuesta44Rdb { get; set; }
        public Nullable<int> estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
