//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_BANDEJA_NOTIFI_DETALLE
    {
        public long IdNotificacion { get; set; }
        public int IdSecuencia { get; set; }
        public string UnidadReplicacion { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> EpisodioClinico { get; set; }
        public Nullable<int> IdEpisodioAtencion { get; set; }
        public Nullable<int> IdComponente { get; set; }
        public string CodigoComponente { get; set; }
        public Nullable<int> Id01 { get; set; }
        public Nullable<int> Id02 { get; set; }
        public string codigo01 { get; set; }
        public string codigo02 { get; set; }
        public string codigo03 { get; set; }
        public string Descripcion01 { get; set; }
        public string Descripcion02 { get; set; }
        public string Descripcion03 { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public Nullable<int> IdOpcion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
