//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_EvolucionObstetricaPuerperio_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdEvolucionPuerperio { get; set; }
        public Nullable<System.DateTime> FechaParto { get; set; }
        public Nullable<System.DateTime> HoraParto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> Obtetriz { get; set; }
        public string Lotep { get; set; }
        public string Areg { get; set; }
        public string Meg { get; set; }
        public string Piel { get; set; }
        public string Mucosas { get; set; }
        public string Mamas { get; set; }
        public string Abdomen { get; set; }
        public string Utero { get; set; }
        public string HeridaOperatoria { get; set; }
        public string Episiorrafia { get; set; }
        public string GenitalesExternos { get; set; }
        public string Loquios { get; set; }
        public string MalOlor { get; set; }
        public string MienbrosInferiores { get; set; }
        public string Miccion { get; set; }
        public string Deposiciones { get; set; }
        public string Medicacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Pulso { get; set; }
        public Nullable<decimal> Respiracion { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<int> PresionArterial1 { get; set; }
        public Nullable<int> PresionArterial2 { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
