//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_EscalaStewart_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdEscalaStewart { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> HoraIngreso { get; set; }
        public Nullable<int> FlagParametro1 { get; set; }
        public Nullable<int> FlagParametro2 { get; set; }
        public Nullable<int> FlagParametro3 { get; set; }
        public Nullable<int> FlagParametro4 { get; set; }
        public Nullable<int> FlagParametro5 { get; set; }
        public Nullable<int> FlagParametro6 { get; set; }
        public Nullable<int> FlagParametro7 { get; set; }
        public Nullable<int> FlagParametro8 { get; set; }
        public Nullable<int> FlagParametro9 { get; set; }
        public Nullable<int> Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
