//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_FichaAnestesia_5_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> GasasCompletas { get; set; }
        public Nullable<int> GasasIncompletas { get; set; }
        public Nullable<int> Respuesta1 { get; set; }
        public Nullable<int> Respuesta2 { get; set; }
        public Nullable<int> Respuesta3 { get; set; }
        public string Paciente_Prov_Otros { get; set; }
        public string Paciente_Dev_Otros { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
