//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Pre_Operatorio_1_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdPreOperatorio2 { get; set; }
        public Nullable<int> TipoCirugia { get; set; }
        public Nullable<int> IdCirujano { get; set; }
        public string NomCirujano { get; set; }
        public Nullable<int> IdEnfermera { get; set; }
        public string NomEnfemera { get; set; }
        public Nullable<int> Servicio { get; set; }
        public Nullable<int> Revisado { get; set; }
        public Nullable<int> Respuesta1 { get; set; }
        public Nullable<int> Respuesta2 { get; set; }
        public Nullable<int> Respuesta3 { get; set; }
        public Nullable<int> Respuesta4 { get; set; }
        public Nullable<int> Respuesta5 { get; set; }
        public Nullable<int> Respuesta6 { get; set; }
        public Nullable<int> Respuesta7 { get; set; }
        public Nullable<int> Respuesta8 { get; set; }
        public Nullable<int> Respuesta9 { get; set; }
        public Nullable<int> Respuesta10 { get; set; }
        public Nullable<int> Respuesta11 { get; set; }
        public Nullable<int> Respuesta12 { get; set; }
        public Nullable<int> Respuesta13 { get; set; }
        public Nullable<int> Respuesta14 { get; set; }
        public Nullable<int> Respuesta15 { get; set; }
        public Nullable<int> Respuesta16 { get; set; }
        public Nullable<int> Respuesta17 { get; set; }
        public Nullable<int> Respuesta18 { get; set; }
        public Nullable<int> Respuesta19 { get; set; }
        public Nullable<int> Respuesta20 { get; set; }
        public Nullable<int> Respuesta21 { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
