//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_UnidadMedida
    {
        public SS_HC_UnidadMedida()
        {
            this.SS_HC_ProcedimientoPrueba = new HashSet<SS_HC_ProcedimientoPrueba>();
        }
    
        public int IdUnidadMedida { get; set; }
        public string CodigoUnidadMedida { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModiicacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Simbolo { get; set; }
    
        public virtual ICollection<SS_HC_ProcedimientoPrueba> SS_HC_ProcedimientoPrueba { get; set; }
    }
    
}
