//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_EnfermedadActual_FE
    {
        public SS_HC_EnfermedadActual_FE()
        {
            this.SS_HC_EnfermedadActualDetalle_FE = new HashSet<SS_HC_EnfermedadActualDetalle_FE>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string TipoAnamnesis { get; set; }
        public string TipoAnamnesisDescrip { get; set; }
        public string MotivoIngreso { get; set; }
        public string FormaInicio { get; set; }
        public string CursoEnfermedad { get; set; }
        public Nullable<int> TiempoEnfermedad { get; set; }
        public string TiempoEnfermedadUnidad { get; set; }
        public string RelatoCronologico { get; set; }
        public string Apetito { get; set; }
        public string Sed { get; set; }
        public string Sudor { get; set; }
        public string Animo { get; set; }
        public string Orina { get; set; }
        public string Orina_Roja { get; set; }
        public string Orina_Espumosa { get; set; }
        public string Orina_Otros { get; set; }
        public string Deposiciones { get; set; }
        public string Deposiciones_Moco { get; set; }
        public string Deposiciones_Sangre { get; set; }
        public string Deposiciones_Otros { get; set; }
        public string Sueño { get; set; }
        public string PesoHabitual { get; set; }
        public Nullable<Decimal> PesoHabitualSub { get; set; }
        public Nullable<System.DateTime> FechaSolicitada { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<SS_HC_EnfermedadActualDetalle_FE> SS_HC_EnfermedadActualDetalle_FE { get; set; }
    }
    
}
