//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ProximaAtencionDiagnostico_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> EpisodioClinico { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> SecuenciaProximaAtencion { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
    
        public virtual SS_HC_ProximaAtencion_FE SS_HC_ProximaAtencion_FE { get; set; }
        public virtual SS_HC_ProximaAtencion_FE SS_HC_ProximaAtencion_FE1 { get; set; }
    }
    
}
