//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_InterConsulta_Epricrisis3_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int Secuencia { get; set; }
        public string ProximaAtencionFlag { get; set; }
        public Nullable<System.DateTime> FechaSolicitada { get; set; }
        public Nullable<System.DateTime> FechaPlaneada { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdTipoInterConsulta { get; set; }
        public Nullable<int> IdTipoReferencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public string CodigoComponente { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> IndicadorEPS { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public string ProcedimientoText { get; set; }
        public string DiagnosticoText { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IndicadorTI { get; set; }
        public string SecuencialHCE { get; set; }
    }
    
}
