//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Anamnesis_AP
    {
        public SS_HC_Anamnesis_AP()
        {
            this.SS_HC_Anamnesis_AP_Detalle = new HashSet<SS_HC_Anamnesis_AP_Detalle>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<short> IdTipoEmbarazo { get; set; }
        public string PatologiaGestacion { get; set; }
        public Nullable<short> IdControlPrenatal { get; set; }
        public Nullable<short> CPnumeroControles { get; set; }
        public Nullable<short> CPnumeroEmbarazos { get; set; }
        public string LugarControl { get; set; }
        public Nullable<short> IdTipoParto { get; set; }
        public string ComplicacionesParto { get; set; }
        public Nullable<short> IdLugarParto { get; set; }
        public Nullable<short> IdPartoAtendidoPor { get; set; }
        public string AntecentesPatologicos { get; set; }
        public Nullable<short> SemanasGestacionNacer { get; set; }
        public Nullable<int> PesoAlNacerGR { get; set; }
        public Nullable<decimal> TallaAlNacerCM { get; set; }
        public Nullable<decimal> PerimetroCefalicoCM { get; set; }
        public string PatologiasPernatales { get; set; }
        public Nullable<short> DiasHospitalizacion { get; set; }
        public Nullable<short> IdTipoLecheHasta6meses { get; set; }
        public string AntecLactancia { get; set; }
        public Nullable<short> EdadInicioAblactanciaMeses { get; set; }
        public string DesarrolloSicomotriz { get; set; }
        public Nullable<System.DateTime> FechaUltimaRegla { get; set; }
        public Nullable<System.DateTime> FechaUltimoPeriodo { get; set; }
        public string MetodosAnticonceptivos { get; set; }
        public string Menarquia { get; set; }
        public string Menopausia { get; set; }
        public string CaracteristicasMenstruaciones { get; set; }
        public string InformacionEmbarazos { get; set; }
        public string Transfusiones { get; set; }
        public Nullable<System.DateTime> DeinmunizFechaAproximada { get; set; }
        public Nullable<int> DeinmunizEdadAproximada { get; set; }
        public string Alcohol { get; set; }
        public string Tabaco { get; set; }
        public string Drogas { get; set; }
        public string ActividadFisica { get; set; }
        public string ConsumoVerduras { get; set; }
        public string ConsumoFrutas { get; set; }
        public string Medicamentos { get; set; }
        public string Alimentos { get; set; }
        public string SustanciasEnElAmbiente { get; set; }
        public string SustanciasContactoConPiel { get; set; }
        public string ContactoPersonaEnferma { get; set; }
        public string CrianzaAnimalesDomesticos { get; set; }
        public string AguaPotable { get; set; }
        public string DisposicionExcretas { get; set; }
        public string ReaccionAdversaMedicamentos { get; set; }
        public string SaludBucal { get; set; }
        public string VigilanciaDeCrecimiento { get; set; }
        public string VigilanciaDelDesarrollo { get; set; }
        public Nullable<short> IdValoracionFuncional1 { get; set; }
        public Nullable<short> IdValoracionFuncional2 { get; set; }
        public Nullable<short> IdValoracionFuncional3 { get; set; }
        public Nullable<short> IdValoracionFuncional4 { get; set; }
        public Nullable<short> IdValoracionFuncional5 { get; set; }
        public Nullable<short> IdValoracionFuncional6 { get; set; }
        public Nullable<short> DiagnosticoFuncional { get; set; }
        public Nullable<short> IdEstadoCognitivo1 { get; set; }
        public Nullable<short> IdEstadoCognitivo2 { get; set; }
        public Nullable<short> IdEstadoCognitivo3 { get; set; }
        public Nullable<short> IdEstadoCognitivo4 { get; set; }
        public Nullable<short> IdEstadoCognitivo5 { get; set; }
        public Nullable<short> IdEstadoCognitivo6 { get; set; }
        public Nullable<short> IdEstadoCognitivo7 { get; set; }
        public Nullable<short> IdEstadoCognitivo8 { get; set; }
        public Nullable<short> IdEstadoCognitivo9 { get; set; }
        public Nullable<short> IdEstadoCognitivo10 { get; set; }
        public Nullable<short> ValoracionCognitiva { get; set; }
        public Nullable<short> IdEstadoAfectivo1 { get; set; }
        public Nullable<short> IdEstadoAfectivo2 { get; set; }
        public Nullable<short> IdEstadoAfectivo3 { get; set; }
        public Nullable<short> IdEstadoAfectivo4 { get; set; }
        public Nullable<short> ConManifestacionesDepresivas { get; set; }
        public Nullable<short> ValoracionSocioFamiliar1 { get; set; }
        public Nullable<short> ValoracionSocioFamiliar2 { get; set; }
        public Nullable<short> ValoracionSocioFamiliar3 { get; set; }
        public Nullable<short> ValoracionSocioFamiliar4 { get; set; }
        public Nullable<short> ValoracionSocioFamiliar5 { get; set; }
        public Nullable<short> ValoracionSocioFamiliar { get; set; }
        public Nullable<short> IdCategoriaAdutoMayor { get; set; }
        public Nullable<short> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
    
        public virtual ICollection<SS_HC_Anamnesis_AP_Detalle> SS_HC_Anamnesis_AP_Detalle { get; set; }
    }
    
}
