//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_UnidadServicio
    {
        public int IdEstablecimientoSalud { get; set; }
        public int IdUnidadServicio { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IndicadorTriaje { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
    
        public virtual SS_HC_CatalogoUnidadServicio SS_HC_CatalogoUnidadServicio { get; set; }
        public virtual SS_HC_EstablecimientoSalud SS_HC_EstablecimientoSalud { get; set; }
        public virtual CM_CO_Establecimiento CM_CO_Establecimiento { get; set; }
    }
    
}
