//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ENFER_VIGI_VentilacionMecanica_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdVentilacionMecanica { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string LavadoManos { get; set; }
        public string LavadoManos_Obs { get; set; }
        public string PosicionSemiFowler { get; set; }
        public string PosicionSemiFowler_Obs { get; set; }
        public string HigieneOral { get; set; }
        public string HigieneOral_Obs { get; set; }
        public string UsoEPP { get; set; }
        public string UsoEPP_Obs { get; set; }
        public string UsoSonda { get; set; }
        public string UsoSonda_Obs { get; set; }
        public string AspiradoCircuitoCerrado { get; set; }
        public string AspiradoCircuitoCerrado_Obs { get; set; }
        public string AspiradoAspiradoSimple { get; set; }
        public string AspiradoAspiradoSimple_Obs { get; set; }
        public string SecresionesTubuladuras { get; set; }
        public string SecresionesTubuladuras_Obs { get; set; }
        public string NivelSecreciones { get; set; }
        public string NivelSecreciones_Obs { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
