//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_CuidadoPreventivo
    {
        public SS_HC_CuidadoPreventivo()
        {
            this.SS_HC_SeguimientoRiesgoDetalle = new HashSet<SS_HC_SeguimientoRiesgoDetalle>();
        }
    
        public int IdCuidadoPreventivo { get; set; }
        public Nullable<int> IdCuidadoPreventivoPadre { get; set; }
        public string CodigoCuidadoPreventivo { get; set; }
        public string CodigoCuidadoPreventivoPadre { get; set; }
        public Nullable<int> IdTipoCuidadoPreventivo { get; set; }
        public Nullable<int> IdTipoPeriodicidad { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string UltimoNivelFlag { get; set; }
        public string CadenaRecursiva { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string NombreTabla { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<SS_HC_SeguimientoRiesgoDetalle> SS_HC_SeguimientoRiesgoDetalle { get; set; }
    }
    
}
