//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_FormatoCampo
    {
        public SS_HC_FormatoCampo()
        {
            this.SS_HC_ControlValidacion = new HashSet<SS_HC_ControlValidacion>();
        }
    
        public int IdFormato { get; set; }
        public int SecuenciaCampo { get; set; }
        public Nullable<int> IdFavoritoTabla { get; set; }
        public Nullable<int> IdCampo { get; set; }
        public Nullable<int> IdSeccionFormato { get; set; }
        public Nullable<int> TipoCampo { get; set; }
        public string ValorPorDefecto { get; set; }
        public Nullable<int> IndicadorObligatorio { get; set; }
        public Nullable<int> IndicadorCampoCalculado { get; set; }
        public string Formula { get; set; }
        public Nullable<int> IndicadorValoresVarios { get; set; }
        public string TablaValoresVarios { get; set; }
        public Nullable<int> IndicadorRango { get; set; }
        public Nullable<decimal> RangoDesde { get; set; }
        public Nullable<decimal> RangoHasta { get; set; }
        public string IndicadorReglaNegocio { get; set; }
        public string ReglaNegocio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<int> IdAgrupadorNivel { get; set; }
        public Nullable<int> IdObjetoAgrupador { get; set; }
        public Nullable<int> IdColumna { get; set; }
        public Nullable<int> IdFila { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> IdParameterEnvio { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdAgrupadorNivelPadre { get; set; }
    
        public virtual SS_HC_SeccionFormato SS_HC_SeccionFormato { get; set; }
        public virtual SS_HC_TablaCampo SS_HC_TablaCampo { get; set; }
        public virtual ICollection<SS_HC_ControlValidacion> SS_HC_ControlValidacion { get; set; }
        public virtual SS_HC_Formato SS_HC_Formato { get; set; }
    }
    
}
