//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Proceso
    {
        public int IdProceso { get; set; }
        public Nullable<int> IdProcesoPadre { get; set; }
        public string CodigoProceso { get; set; }
        public string TipoProceso { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public string NombreInterfaz { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string UltimoNivelFlag { get; set; }
        public string CadenaRecursividad { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Icono { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
    
}
