//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_TablaCampo
    {
        public SS_HC_TablaCampo()
        {
            this.SS_HC_FormatoCampo = new HashSet<SS_HC_FormatoCampo>();
        }
    
        public int IdFavoritoTabla { get; set; }
        public int IdCampo { get; set; }
        public string NombreCampo { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> TipoCampo { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Decimales { get; set; }
        public Nullable<int> NumeroClavePrimaria { get; set; }
        public Nullable<int> TipoCampoDescripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<SS_HC_FormatoCampo> SS_HC_FormatoCampo { get; set; }
        public virtual SS_HC_Tabla SS_HC_Tabla { get; set; }
    }
    
}
