//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_KardexEnfermeriaDetalle
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdOrdenAtencion { get; set; }
        public int Secuencia { get; set; }
        public string UnidadReplicacionReferencia { get; set; }
        public Nullable<long> IdEpisodioAtencionReferencia { get; set; }
        public Nullable<int> IdPacienteReferencia { get; set; }
        public Nullable<int> EpisodioClinicoReferencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public Nullable<System.DateTime> HoraInicioProg { get; set; }
        public string HorasProgramadas { get; set; }
        public string HorasSuministradas { get; set; }
        public string EnfermeraSuministro { get; set; }
        public string Linea { get; set; }
        public string Familia { get; set; }
        public string SubFamilia { get; set; }
        public string TipoComponente { get; set; }
        public string CodigoComponente { get; set; }
        public Nullable<int> GrupoMedicamento { get; set; }
        public Nullable<int> SituacionRegistro { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
