//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Nota_Ingreso_FE
    {
        public SS_HC_Nota_Ingreso_FE()
        {
            this.SS_HC_NotaIngreso_ExamenApoyo_FE = new HashSet<SS_HC_NotaIngreso_ExamenApoyo_FE>();
            this.SS_HC_NotaIngreso_Diagnostico_FE = new HashSet<SS_HC_NotaIngreso_Diagnostico_FE>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string GradoAsistencia { get; set; }
        public string MotivoIngreso { get; set; }
        public string GradoAsistencia_Enfermedad { get; set; }
        public string CursoEnfermedad { get; set; }
        public Nullable<int> TiempoEnfermedad { get; set; }
        public string TiempoEnfermedadUnidad { get; set; }
        public string RelatoCronologico { get; set; }
        public Nullable<int> PresionArterialMSD1 { get; set; }
        public Nullable<int> PresionArterialMSD2 { get; set; }
        public Nullable<int> PresionArterialMSI { get; set; }
        public Nullable<int> PresionArterialMS2 { get; set; }
        public Nullable<decimal> FrecuenciaCardiaca { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<int> SaturacionOxigeno { get; set; }
        public Nullable<int> Fi02 { get; set; }
        public Nullable<int> FrecuenciaCardFetal_Flag { get; set; }
        public Nullable<int> FrecuenciaCard_FetalAdd { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> Talla { get; set; }
        public Nullable<decimal> IMC { get; set; }
        public string Antecedentes_Importancia { get; set; }
        public string Examen_Fisico { get; set; }
        public string Plantrabajo_Inicial { get; set; }
        public string Cristerios_Hospitalizacion { get; set; }
        public string Comentarios { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<SS_HC_NotaIngreso_ExamenApoyo_FE> SS_HC_NotaIngreso_ExamenApoyo_FE { get; set; }
        public virtual ICollection<SS_HC_NotaIngreso_Diagnostico_FE> SS_HC_NotaIngreso_Diagnostico_FE { get; set; }
    }
    
}
