//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_FichaAnestesia_1_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> NSop { get; set; }
        public string TipoProcedimiento { get; set; }
        public string AntecedentesPersonales { get; set; }
        public string Glucosa { get; set; }
        public string VDRL { get; set; }
        public string PSA { get; set; }
        public string Hb { get; set; }
        public string Hcto { get; set; }
        public string UreaCreat { get; set; }
        public string PLAQ { get; set; }
        public string PTPIT { get; set; }
        public string INR { get; set; }
        public string GrupoSanguineo { get; set; }
        public string FactorRH { get; set; }
        public string RiesgoQuirurgico { get; set; }
        public string RiesgoQuirurgico2 { get; set; }
        public string RiesgoNeumologico { get; set; }
        public string RiesgoNeumologico2 { get; set; }
        public string ASA { get; set; }
        public string ASA2 { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public Nullable<int> Anestesiologo { get; set; }
        public Nullable<int> Ayudante { get; set; }
        public Nullable<int> EnfInstrumentista { get; set; }
        public Nullable<int> EnfCirculante { get; set; }
        public Nullable<int> Neonatologo { get; set; }
        public Nullable<int> Cardiologo { get; set; }
        public string Ayuno { get; set; }
        public string EstomagoLleno { get; set; }
     
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }

}
