//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_BalanceHidroElect_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int TipoBalance { get; set; }
        public Nullable<System.DateTime> FechaControl { get; set; }
        public Nullable<int> Turno { get; set; }
        public Nullable<int> Drenaje { get; set; }
        public Nullable<int> Autolisis { get; set; }


        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> Hora { get; set; }
        public Nullable<decimal> AlimentacionOral { get; set; }
        public Nullable<decimal> SNG { get; set; }
        public string DetalleSNG { get; set; }
        public Nullable<decimal> TotalIngresos { get; set; }
        public Nullable<int> PerdidaInsensible { get; set; }
        public Nullable<decimal> PerdidaCantidad { get; set; }
        public Nullable<decimal> Orina { get; set; }
        public Nullable<decimal> Heces { get; set; }
        public Nullable<decimal> Vomitos { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public string TemperaturaDescripcion { get; set; }
        public Nullable<decimal> SuperficieCorporal { get; set; }
        public string SuperficieDescripion { get; set; }
        public Nullable<decimal> Succion { get; set; }
        public Nullable<decimal> PerdidaSNG { get; set; }
        public Nullable<decimal> TotalEgresos { get; set; }
        public Nullable<decimal> BalanceHidrico { get; set; }
        public Nullable<decimal> BalanceAcumulado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
