//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Favorito
    {
        public SS_HC_Favorito()
        {
            this.SS_HC_FavoritoCodigoId = new HashSet<SS_HC_FavoritoCodigoId>();
            this.SS_HC_FavoritoNumero = new HashSet<SS_HC_FavoritoNumero>();
        }
    
        public int IdFavorito { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> TipoFavorito { get; set; }
        public Nullable<int> IdFavoritoTabla { get; set; }
        public Nullable<int> IdAgente { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual SS_HC_Tabla SS_HC_Tabla { get; set; }
        public virtual ICollection<SS_HC_FavoritoCodigoId> SS_HC_FavoritoCodigoId { get; set; }
        public virtual ICollection<SS_HC_FavoritoNumero> SS_HC_FavoritoNumero { get; set; }
        public virtual SG_Agente SG_Agente { get; set; }
    }
    
}
