//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_BANDEJA_NOTIFI_HEADER
    {
        public long IdNotificacion { get; set; }
        public string UnidadReplicacion { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> EpisodioClinico { get; set; }
        public Nullable<int> IdEpisodioAtencion { get; set; }
        public Nullable<int> Linea { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public string TipoNotificacion { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public Nullable<int> IdOpcion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
