//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Epidemiologia_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string GeresaDiresaDiris { get; set; }
        public string Eess { get; set; }
        public string InstAdm { get; set; }
        public string Clasificacioncaso { get; set; }
        public string Detectadopuntoentrada1 { get; set; }
        public Nullable<System.DateTime> Detectadopuntoentrada2 { get; set; }
        public string Detectadopuntoentrada3 { get; set; }
        public string Telefono { get; set; }
        public string CasoDiagnosticado1 { get; set; }
        public string CasoDiagnosticado2 { get; set; }
        public string CasoDiagnosticado3 { get; set; }
        public string DireccionResidencia { get; set; }
        public string ResidenciaPais { get; set; }
        public string ResidenciaProvincia { get; set; }
        public string ResidenciaDistrito { get; set; }
        public Nullable<System.DateTime> Fechainiciosintomas { get; set; }
        public string Fechainiciosintomasdescripcion { get; set; }
        public string Hospitalizado { get; set; }
        public Nullable<System.DateTime> Fechahospitalizacion { get; set; }
        public string Aislamiento { get; set; }
        public Nullable<System.DateTime> FechaAislamiento { get; set; }
        public string Pacienteventilacionmecanica { get; set; }
        public string Evolucionpaciente { get; set; }
        public Nullable<System.DateTime> FechaDefuncion { get; set; }
        public string SintomasFiebre { get; set; }
        public string SintomasMalestar { get; set; }
        public string SintomasTos { get; set; }
        public string SintomasDolorGarganta { get; set; }
        public string SintomasCongestionNasal { get; set; }
        public string SintomasOtros { get; set; }
        public string SintonmasEspecificar { get; set; }
        public string SintomasDificultad { get; set; }
        public string SintomasDiarrea { get; set; }
        public string SintomasNauseas { get; set; }
        public string SintomasCefalea { get; set; }
        public string SintomasIrritabilidad { get; set; }
        public string SintomasDolor { get; set; }
        public string DolorMuscular { get; set; }
        public string DolorAbdominal { get; set; }
        public string DolorPecho { get; set; }
        public string DolorArticulaciones { get; set; }
        public Nullable<decimal> SignosTemperatura { get; set; }
        public string SignosExudadoFarigeo { get; set; }
        public string SignosInyeccionConjuntival { get; set; }
        public string SignosConvulsion { get; set; }
        public string SignosOtros { get; set; }
        public string SignosEspecificar { get; set; }
        public string SignosComa { get; set; }
        public string SignosDisnea { get; set; }
        public string SignosAuscultacion { get; set; }
        public string SignosHallazgosRx { get; set; }
        public string ComorbilidadEmbarazo { get; set; }
        public string ComorbilidadTrimestre { get; set; }
        public string ComorbilidadCardiovascular { get; set; }
        public string ComorbilidadDiabetes { get; set; }
        public string ComorbilidadEnfermedadHepatica { get; set; }
        public string ComorbilidadEnfermedadCronica { get; set; }
        public string ComorbilidadOtros { get; set; }
        public string ComorbilidadEspecificar { get; set; }
        public string ComorbilidadPosParto { get; set; }
        public string ComorbilidadInmunodeficiencia { get; set; }
        public string ComorbilidadEnfermedadRenal { get; set; }
        public string ComorbilidadDanoHepatico { get; set; }
        public string ComorbilidadEnfermedadPulmonar { get; set; }
        public string ComorbilidadCancer { get; set; }
        public string OcupacionEstudiante { get; set; }
        public string OcupacionTrabajaAnimales { get; set; }
        public string OcupacionTrabajaSaludLaboratorio { get; set; }
        public string OcupacionTrabajadorSalud { get; set; }
        public string OcupacionOtros { get; set; }
        public string OcupacionEspecificar { get; set; }
        public string PacienteInicioSintomas { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string EstablecimientoSaludPrevio { get; set; }
        public string EstablecimientoSaludPrevioDescri { get; set; }
        public string InfeccionEntornoSalud { get; set; }
        public string InfeccionDesconocido { get; set; }
        public string InfeccionEntornoFamiliar { get; set; }
        public string InfeccionOtros { get; set; }
        public string InfeccionEspecificar { get; set; }
        public string InfeccionLugarTrabajo { get; set; }
        public string InfeccionLugarTrabajoDescri { get; set; }
        public string VisitaMercado { get; set; }
        public string VisitaMercadoSi { get; set; }
        public Nullable<System.DateTime> FechaMuestra { get; set; }
        public string TipoMuestra { get; set; }
        public string Secuenciamiento { get; set; }
        public Nullable<System.DateTime> ResultadoLaboratorio { get; set; }
        public string NombreHospital { get; set; }
        public string ExposicionLugar { get; set; }
        public string Sintomas14Dias { get; set; }
        public string Sintomas14Entorno { get; set; }
        public string Sintomas14Desconocido { get; set; }
        public string Sintomas14EntornoFamiliar { get; set; }
        public string Sintomas14Otros { get; set; }
        public string Sintomas14Especifique { get; set; }
        public string LugarTrabajo { get; set; }
        public string LugarTrabajoDescri { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Accion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Version { get; set; }
        public string TipoPrueba { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string PersllenaFicha { get; set; }
        public string FirmaSello { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
    }
    
}
