//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_DescansoMedico_FE
    {
        public SS_HC_DescansoMedico_FE()
        {
            this.SS_HC_DescansoMedico_Diagnostico_FE = new HashSet<SS_HC_DescansoMedico_Diagnostico_FE>();
            this.SS_HC_InformeAlta_Examen_FE = new HashSet<SS_HC_InformeAlta_Examen_FE>();
            this.SS_HC_Apoyo_Diagnostico_FE = new HashSet<SS_HC_Apoyo_Diagnostico_FE>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<System.DateTime> FechaInicioDescanso { get; set; }
        public Nullable<System.DateTime> FechaFinDescanso { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public Nullable<int> IdFormaInicio { get; set; }
    
        public virtual ICollection<SS_HC_DescansoMedico_Diagnostico_FE> SS_HC_DescansoMedico_Diagnostico_FE { get; set; }
        public virtual ICollection<SS_HC_InformeAlta_Examen_FE> SS_HC_InformeAlta_Examen_FE { get; set; }
        public virtual ICollection<SS_HC_Apoyo_Diagnostico_FE> SS_HC_Apoyo_Diagnostico_FE { get; set; }
    }
    
}
