//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ENFER_VIGI_CATETERURINARIO_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdCateterUrinario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string LavadoManos { get; set; }
        public string LavadoManos_Obs { get; set; }
        public string UsoGuantes { get; set; }
        public string UsoGuantes_Obs { get; set; }
        public string SistemaCerrado { get; set; }
        public string SistemaCerrado_Obs { get; set; }
        public string BolsaFija { get; set; }
        public string BolsaFija_Obs { get; set; }
        public string BolsaEncima { get; set; }
        public string BolsaEncima_Obs { get; set; }
        public string LavadoGenital { get; set; }
        public string LavadoGenital_Obs { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
