//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ExamenFisico_Triaje
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> PresionMinima { get; set; }
        public Nullable<int> PresionMaxima { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<int> FrecuenciaCardiaca { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<decimal> IndiceMasaCorporal { get; set; }
        public Nullable<int> IdEstadoGeneral { get; set; }
        public Nullable<int> IdNutricion { get; set; }
        public Nullable<int> IdHidratacion { get; set; }
        public Nullable<int> IdColaboracion { get; set; }
        public string ObservacionesAdicionales { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
