//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_HojaRecienNacido_FE
    {
        public long IdEpisodioAtencion { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> IdRecienNacido { get; set; }
        public string NombreNacido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public System.DateTime HoraNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Grupo { get; set; }
        public string FactorRH { get; set; }
        public string Coombs { get; set; }
        public string NombrePadre { get; set; }
        public Nullable<int> EdadPadre { get; set; }
        public string NombreMadre { get; set; }
        public Nullable<int> EdadMadre { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> RPRFlat { get; set; }
        public Nullable<System.DateTime> RPRFecha { get; set; }
        public Nullable<int> HIVFlat { get; set; }
        public Nullable<System.DateTime> HIVFecha { get; set; }
        public string GrupoSanguineo { get; set; }
        public string RH { get; set; }
        public string Gravidez { get; set; }
        public string Paridad { get; set; }
        public Nullable<int> NroCesarea { get; set; }
        public Nullable<System.DateTime> FechaUltima { get; set; }
        public string Natimuertos { get; set; }
        public string Prematuros { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Enfermedades { get; set; }
        public Nullable<System.DateTime> FUR { get; set; }
        public Nullable<int> NroControl { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> NroSemana { get; set; }
        public Nullable<int> NroDuracion { get; set; }
        public Nullable<int> MembranasFlat { get; set; }
        public Nullable<System.DateTime> HoraDuracion { get; set; }
        public Nullable<System.DateTime> HoraMembranas { get; set; }
        public string Analgesico { get; set; }
        public string Anestecia { get; set; }
        public Nullable<int> TipoParto { get; set; }
        public string Posicion { get; set; }
        public string Medicamentos { get; set; }
        public string Placenta { get; set; }
        public string Liquidos { get; set; }
        public string Otros { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
    
}
