//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ReferenciaDetalle_FE
    {
        public long IdEpisodioAtencion { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdReferencia { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual SS_HC_Referencia_FE SS_HC_Referencia_FE { get; set; }
    }
    
}
