//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_HojaRecienNacidoDetalle_FE
    {
        public long IdEpisodioAtencion { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> IdRecienNacido { get; set; }
        public int IdSecuencia { get; set; }
        public string Tiempo { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<int> Esfuerzo { get; set; }
        public Nullable<int> Tono { get; set; }
        public Nullable<int> Irritabilidad { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Total { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
    
}
