//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_ExamenSolicitadoFE
    {
        public SS_HC_ExamenSolicitadoFE()
        {
            this.SS_HC_ExamenSolicitadoDet_FE = new HashSet<SS_HC_ExamenSolicitadoDet_FE>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public string Resumen { get; set; }
        public string Motivo { get; set; }
        public string TipoExamen { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> IdProcedimientoCab { get; set; }
        public Nullable<System.DateTime> FechaSolitadaCab { get; set; }
        public Nullable<int> CantidadCab { get; set; }
        public string ObservacionCab { get; set; }
        public Nullable<int> IndicadorEPSCab { get; set; }
        public string TipoCodigoCab { get; set; }
        public string CodigoSegusCab { get; set; }
        public string CodigoComponenteCab { get; set; }
        public Nullable<int> IdEspecialidadCab { get; set; }
        public Nullable<int> SecuenciaCab { get; set; }
        public string EspecificacionesCab { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
    
        public virtual ICollection<SS_HC_ExamenSolicitadoDet_FE> SS_HC_ExamenSolicitadoDet_FE { get; set; }
    }
    
}
