//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_FichaAnestesia_2_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> Respuesta1 { get; set; }
        public Nullable<int> Respuesta2 { get; set; }
        public Nullable<int> Respuesta3 { get; set; }
        public Nullable<int> Respuesta4 { get; set; }
        public Nullable<int> Respuesta5 { get; set; }
        public Nullable<int> Respuesta6 { get; set; }
        public Nullable<int> Respuesta7 { get; set; }
        public Nullable<int> Respuesta8 { get; set; }
        public Nullable<int> Respuesta9 { get; set; }
        public Nullable<int> Respuesta10 { get; set; }
        public Nullable<int> Respuesta11 { get; set; }
        public Nullable<int> Respuesta12 { get; set; }
        public Nullable<int> Respuesta13 { get; set; }
        public Nullable<int> Respuesta14 { get; set; }
        public Nullable<int> Respuesta15 { get; set; }
        public Nullable<int> Respuesta16 { get; set; }
        public Nullable<int> Respuesta17 { get; set; }
        public Nullable<int> Respuesta18 { get; set; }
        public Nullable<int> Respuesta19 { get; set; }
        public Nullable<int> Respuesta20 { get; set; }
        public Nullable<int> TET { get; set; }
        public Nullable<int> M_Facial { get; set; }
        public Nullable<int> M_Laringea { get; set; }
        public Nullable<int> Respuesta21 { get; set; }
        public Nullable<int> Respuesta22 { get; set; }
        public Nullable<int> Respuesta23 { get; set; }
        public Nullable<int> Respuesta24 { get; set; }
        public Nullable<int> Respuesta25 { get; set; }
        public Nullable<int> Respuesta26 { get; set; }
        public Nullable<int> Respuesta27 { get; set; }
        public Nullable<int> Respuesta28 { get; set; }
        public Nullable<int> Respuesta29 { get; set; }
        public Nullable<int> Respuesta30 { get; set; }
        public Nullable<int> Respuesta31 { get; set; }
        public Nullable<decimal> CATVenoso { get; set; }
        public Nullable<decimal> PVCCAT { get; set; }
        public Nullable<int> Respuesta32 { get; set; }
        public Nullable<int> Respuesta33 { get; set; }
        public Nullable<int> Respuesta34 { get; set; }
        public Nullable<int> Respuesta35 { get; set; }
        public Nullable<int> Respuesta36 { get; set; }
        public Nullable<int> Respuesta37 { get; set; }
        public Nullable<int> Respuesta38 { get; set; }
        public Nullable<int> Respuesta39 { get; set; }
        public Nullable<int> Respuesta40 { get; set; }
        public Nullable<int> Respuesta41 { get; set; }
        public string Posicion_Otros { get; set; }
        public Nullable<System.DateTime> Fec_Ini_Anestesia { get; set; }
        public Nullable<System.DateTime> Hor_Ini_Anestesia { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Anestesia { get; set; }
        public Nullable<System.DateTime> Hor_Fin_Anestesia { get; set; }
        public Nullable<System.DateTime> Fec_Ini_Cirugia { get; set; }
        public Nullable<System.DateTime> Hor_Ini_Cirugia { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Cirugia { get; set; }
        public Nullable<System.DateTime> Hor_Fin_Cirugia { get; set; }
        public Nullable<int> Respuesta42 { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
