//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_SeguridadCirugia_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdSeguridad { get; set; }
        public int TipoCirugia { get; set; }
        public string IntervencionQ { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> Respuesta1 { get; set; }
        public Nullable<int> Respuesta2 { get; set; }
        public Nullable<int> Respuesta3 { get; set; }
        public Nullable<int> Respuesta4 { get; set; }
        public Nullable<int> Respuesta5 { get; set; }
        public Nullable<int> Respuesta6 { get; set; }
        public Nullable<int> Respuesta7 { get; set; }
        public Nullable<int> Respuesta8 { get; set; }
        public Nullable<int> Respuesta9 { get; set; }
        public Nullable<int> Respuesta10 { get; set; }
        public Nullable<int> Respuesta11 { get; set; }
        public Nullable<int> Respuesta12 { get; set; }
        public Nullable<int> Respuesta13 { get; set; }
        public Nullable<int> Respuesta14 { get; set; }
        public string Antibiotico { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    }
    
}
