//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_CatalogoUnidadServicio_TipoAtencion
    {
        public int IdUnidadServicio { get; set; }
        public int IdTipoAtencion { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
    
        public virtual SS_GE_TipoAtencion SS_GE_TipoAtencion { get; set; }
        public virtual SS_HC_CatalogoUnidadServicio SS_HC_CatalogoUnidadServicio { get; set; }
    }
    
}
