//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_FavoritoDetalle
    {
        public int IdFavorito { get; set; }
        public int NumeroFavorito { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> ValorId { get; set; }
        public string ValorTexto1 { get; set; }
        public string ValorTexto2 { get; set; }
        public string ValorTexto3 { get; set; }
        public string ValorTexto4 { get; set; }
        public string ValorTexto5 { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual SS_HC_FavoritoNumero SS_HC_FavoritoNumero { get; set; }
    }
    
}
