//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Referencia_FE
    {
        public SS_HC_Referencia_FE()
        {
            this.SS_HC_ReferenciaDetalle_FE = new HashSet<SS_HC_ReferenciaDetalle_FE>();
        }
    
        public long IdEpisodioAtencion { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int IdReferencia { get; set; }
        public string NroReferencia { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string EstablecimientoOri { get; set; }
        public string ServicioOri { get; set; }
        public string EstablecimientoDest { get; set; }
        public string ServicioDest { get; set; }
        public string IdentificacionUsu { get; set; }
        public string Anamnesis { get; set; }
        public string EstadoGeneral { get; set; }
        public string Glasgow { get; set; }
        public string FV_T { get; set; }
        public string FV_PA { get; set; }
        public string FV_FR { get; set; }
        public string FV_FC { get; set; }
        public string Tratamiento { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> TipoAtencionRef { get; set; }
        public Nullable<System.DateTime> FechaReferencia { get; set; }
        public Nullable<System.DateTime> HoraReferencia { get; set; }
        public string PersonaAtiende { get; set; }
        public Nullable<int> CondicionSalida { get; set; }
        public string MedicoSanna { get; set; }
        public string MedicoAtencion { get; set; }
        public Nullable<int> IdResponsableRef { get; set; }
        public Nullable<int> IdResponsableSer { get; set; }
        public Nullable<int> IdResponsableAco { get; set; }
        public string IdResponsableRec { get; set; }
        public Nullable<int> Condicionllegada { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ExamenesAux { get; set; }
    
        public virtual ICollection<SS_HC_ReferenciaDetalle_FE> SS_HC_ReferenciaDetalle_FE { get; set; }
    }
    
}
