//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_CONTRARREFERENCIA_FE
    {
        public SS_HC_CONTRARREFERENCIA_FE()
        {
            this.SS_HC_CONTRARREFERENCIA_Diagnostico_FE = new HashSet<SS_HC_CONTRARREFERENCIA_Diagnostico_FE>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<long> NroContrarreferencia { get; set; }
        public Nullable<System.DateTime> FechaContrarreferencia { get; set; }
        public Nullable<System.DateTime> HoraContrarreferencia { get; set; }
        public string EstablecimientoOrigen { get; set; }
        public string ServicioOrigen { get; set; }
        public string EstablecimientoDestino { get; set; }
        public string ServicioDestino { get; set; }
        public string IdentificacionUsuario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public string TratamientoRealizados { get; set; }
        public string ProcedimientosRealizados { get; set; }
        public string Origen { get; set; }
        public string Calificacion { get; set; }
        public string UPSContrarreferencia { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string Recomendaciones { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public string CondicionPaciente { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<SS_HC_CONTRARREFERENCIA_Diagnostico_FE> SS_HC_CONTRARREFERENCIA_Diagnostico_FE { get; set; }
    }
    
}
