//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_SG_MaestroCobertura
    {
        public int IdCobertura { get; set; }
        public string CodigoCobertura { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IndicadorAmbulatorio { get; set; }
        public Nullable<int> IndicadorEmergencia { get; set; }
        public Nullable<int> IndicadorHospitalario { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Coderam { get; set; }
        public Nullable<int> TipoTabla { get; set; }
        public string ACCION { get; set; }
        public string VERSION { get; set; }
    }
    
}
