//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class VW_FORMATORECURSOCAMPO
    {
        public int IdFormato { get; set; }
        public string CodigoFormato { get; set; }
        public string DescripcionFormato { get; set; }
        public int SecuenciaCampo { get; set; }
        public string DescripFormatoCampo { get; set; }
        public string Formula { get; set; }
        public int IdFavoritoTabla { get; set; }
        public string DescripcionTabla { get; set; }
        public string DescripTablaCampo { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Accion { get; set; }
    }
    
}
