//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class VW_SS_HC_TABLAFORMATO_VALIDACION
    {
        public int IdFormato { get; set; }
        public Nullable<int> FormatoNivelID { get; set; }
        public Nullable<int> IdFormatoPadre { get; set; }
        public string CodigoFormato { get; set; }
        public string CodigoFormatoPadre { get; set; }
        public string DescripcionFormato { get; set; }
        public Nullable<int> TipoFormato { get; set; }
        public Nullable<int> EstadoFormato { get; set; }
        public int IdFavoritoTabla { get; set; }
        public string NombreTabla { get; set; }
        public string DescripcionTabla { get; set; }
        public Nullable<int> TipoTabla { get; set; }
        public Nullable<int> EstadoTabla { get; set; }
        public int IdCampo { get; set; }
        public string NombreCampo { get; set; }
        public string DescripcionCampo { get; set; }
        public Nullable<int> TipoCampo { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Decimales { get; set; }
        public Nullable<int> EstadoTablaCampo { get; set; }
        public int SecuenciaCampo { get; set; }
        public Nullable<int> IdSeccionFormato { get; set; }
        public string ValorPorDefecto { get; set; }
        public Nullable<int> IndicadorObligatorio { get; set; }
        public Nullable<int> IndicadorCampoCalculado { get; set; }
        public string Formula { get; set; }
        public Nullable<int> IndicadorValoresVarios { get; set; }
        public string TablaValoresVarios { get; set; }
        public Nullable<int> IndicadorRango { get; set; }
        public Nullable<decimal> RangoDesde { get; set; }
        public Nullable<decimal> RangoHasta { get; set; }
        public string IndicadorReglaNegocio { get; set; }
        public string ReglaNegocio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> EstadoFormatoCampo { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<int> IdAgrupadorNivel { get; set; }
        public Nullable<int> IdObjetoAgrupador { get; set; }
        public Nullable<int> IdColumna { get; set; }
        public Nullable<int> IdFila { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> IdParameterEnvio { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdAgrupadorNivelPadre { get; set; }
        public Nullable<int> SecuenciaValidacion { get; set; }
        public Nullable<int> IdComponente { get; set; }
        public Nullable<int> IdAtributo { get; set; }
        public string TipoValidacion { get; set; }
        public string FlagTipoDato { get; set; }
        public string ValorTexto { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public Nullable<System.DateTime> ValorDate { get; set; }
        public Nullable<int> SecuenciaValidacionRef { get; set; }
        public Nullable<int> EstadoValidacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string NombreComponente { get; set; }
        public string TipoComponente { get; set; }
        public Nullable<int> EstadoComponente { get; set; }
        public string NombreAtributo { get; set; }
        public Nullable<int> EstadoAtributo { get; set; }
        public string IdiomaProperty { get; set; }
    }
    
}
