//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class WH_Condicion
    {
        public WH_Condicion()
        {
            this.WH_ItemAlmacen = new HashSet<WH_ItemAlmacen>();
        }
    
        public string Condicion { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionIngles { get; set; }
        public Nullable<float> Porcentaje { get; set; }
        public string CuentaInventario { get; set; }
        public string NoControlableFlag { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual ICollection<WH_ItemAlmacen> WH_ItemAlmacen { get; set; }
    }
    
}
