//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class WH_ItemAlmacen
    {
        public WH_ItemAlmacen()
        {
            this.WH_ItemAlmacenLote = new HashSet<WH_ItemAlmacenLote>();
        }
    
        public string Item { get; set; }
        public string Condicion { get; set; }
        public string AlmacenCodigo { get; set; }
        public string UbicacionFisica { get; set; }
        public string UbicacionFisica02 { get; set; }
        public string UbicacionFisica03 { get; set; }
        public Nullable<int> StockPedido { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public Nullable<int> StockMaximo { get; set; }
        public Nullable<int> StockPuntoReorden { get; set; }
        public Nullable<int> TiempoEspera { get; set; }
        public string ValidacionPedidoComercialFlag { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string UltimoUsuario { get; set; }
        public string indicadorItemVentaNormal { get; set; }
        public string indicadorItemVentaProteccion { get; set; }
        public string indicadorItemVentaConsignacion { get; set; }
        public Nullable<int> cantidadMinimaConsignacion { get; set; }
        public Nullable<int> cantidadMinimaProteccion { get; set; }
        public Nullable<int> ConsumoPromedio { get; set; }
        public Nullable<int> StockMinimoPromedio { get; set; }
        public Nullable<int> StockPuntoReordenPromedio { get; set; }
        public Nullable<int> StockMaximoPromedio { get; set; }
        public Nullable<int> DiasMinimo { get; set; }
        public Nullable<int> DiasPunto { get; set; }
        public Nullable<int> DiasMaximo { get; set; }
        public string recomendadomodalidad { get; set; }
    
        public virtual WH_AlmacenMast WH_AlmacenMast { get; set; }
        public virtual WH_Condicion WH_Condicion { get; set; }
        public virtual ICollection<WH_ItemAlmacenLote> WH_ItemAlmacenLote { get; set; }
    }
    
}
