//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class WH_LoteEquivalente
    {
        public WH_LoteEquivalente()
        {
            this.WH_ItemAlmacenLote = new HashSet<WH_ItemAlmacenLote>();
        }
    
        public string LoteEquivalente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> CantidadEquivalente { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
    
        public virtual ICollection<WH_ItemAlmacenLote> WH_ItemAlmacenLote { get; set; }
    }
    
}
