//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class CM_CO_TablaMaestroDetalleConcepto
    {
        public int IdTablaMaestro { get; set; }
        public int IdCodigo { get; set; }
        public int Secuencial { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string Version { get; set; }
        public Nullable<int> IndicadorConcepto { get; set; }
        public string Moneda { get; set; }
        public string TipoDato { get; set; }
        public Nullable<decimal> ValorInicialN { get; set; }
        public Nullable<decimal> ValorFinalN { get; set; }
        public string ValorTexto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> ValorInicialFecha { get; set; }
        public Nullable<System.DateTime> ValorFinalFecha { get; set; }
        public string Accion { get; set; }
    
        public virtual CM_CO_TablaMaestroConcepto CM_CO_TablaMaestroConcepto { get; set; }
        public virtual CM_CO_TablaMaestroDetalle CM_CO_TablaMaestroDetalle { get; set; }
    }
    
}
