//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class HC_SubProcesoSelector
    {
        public int SubProcesoSelector { get; set; }
        public string SubProceso { get; set; }
        public string CodigoSelector { get; set; }
    }
    
}
