//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SEGURIDADCONCEPTO
    {
        public SEGURIDADCONCEPTO()
        {
            this.SS_HC_Selector = new HashSet<SS_HC_Selector>();
        }
    
        public string APLICACIONCODIGO { get; set; }
        public string GRUPO { get; set; }
        public string CONCEPTO { get; set; }
        public string CONCEPTOPADRE { get; set; }
        public Nullable<int> IDPAGINA { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESCRIPCIONINGLES { get; set; }
        public string VISIBLEFLAG { get; set; }
        public string TIPODEDETALLE { get; set; }
        public string TIPODEOBJETO { get; set; }
        public string OBJETO { get; set; }
        public string TIPODEACCESO { get; set; }
        public string OBJETOWINDOW { get; set; }
        public string WORKFLAG { get; set; }
        public string WORKAGREGARFLAG { get; set; }
        public string WORKMODIFICARFLAG { get; set; }
        public string WORKBORRARFLAG { get; set; }
        public string WORKAPROBARFLAG { get; set; }
        public string WEBFLAG { get; set; }
        public string WEBPAGE { get; set; }
        public string WEBACTION { get; set; }
        public string WEBGRUPO { get; set; }
        public Nullable<int> WEBGRUPOSECUENCIA { get; set; }
        public string ULTIMOUSUARIO { get; set; }
        public Nullable<System.DateTime> ULTIMAFECHAMODIF { get; set; }
        public string ESTADO { get; set; }
        public string ACCION { get; set; }
    
        public virtual SEGURIDADGRUPO SEGURIDADGRUPO { get; set; }
        public virtual ICollection<SS_HC_Selector> SS_HC_Selector { get; set; }
    }
    
}
