//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SG_Opcion
    {
        public int IdOpcion { get; set; }
        public Nullable<int> IdOpcionPadre { get; set; }
        public string CodigoOpcion { get; set; }
        public string CadenaRecursividad { get; set; }
        public Nullable<int> NivelOpcion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Sistema { get; set; }
        public string Modulo { get; set; }
        public string SubModulo { get; set; }
        public Nullable<int> Orden { get; set; }
        public string TipoOpcion { get; set; }
        public Nullable<int> TipoIcono { get; set; }
        public Nullable<int> IndicadorPrioridad { get; set; }
        public Nullable<int> IndicadorObjeto { get; set; }
        public Nullable<int> IdObjetoAsociado { get; set; }
        public string TipoDato { get; set; }
        public string ValorTexto { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
        public string UrlOpcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Compania { get; set; }
        public Nullable<int> IndicadorCompania { get; set; }
    }
    
}
