//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_GE_ProcedimientoMedicoDos
    {
        public int IdProcedimientoDos { get; set; }
        public string CodigoProcedimientoDos { get; set; }
        public string CodigoPadre { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdProcedimientoDosPadre { get; set; }
        public Nullable<int> Orden { get; set; }
        public string CadenaRecursividad { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string DiagnosticoSiteds { get; set; }
        public Nullable<int> IndicadorPermitido { get; set; }
        public Nullable<int> tipofolder { get; set; }
        public string NombreTabla { get; set; }
    }
    
}
