//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_SeccionCampo
    {
        public int IdSeccionCampo { get; set; }
        public int IdSeccion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string NombreTabla { get; set; }
        public string NombreCampo { get; set; }
        public string NombreTablaMaestro { get; set; }
        public string NombreCampoMaestro { get; set; }
        public string HayValoresFlag { get; set; }
        public string ReglaValidacion { get; set; }
        public string ReglaPresentacion { get; set; }
    
        public virtual SS_HC_Seccion SS_HC_Seccion { get; set; }
    }
    
}
