//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Tabla
    {
        public SS_HC_Tabla()
        {
            this.SS_HC_Seccion = new HashSet<SS_HC_Seccion>();
            this.SS_HC_TablaCampo = new HashSet<SS_HC_TablaCampo>();
        }
    
        public string NombreTabla { get; set; }
        public string TablaFlag { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
    
        public virtual ICollection<SS_HC_Seccion> SS_HC_Seccion { get; set; }
        public virtual ICollection<SS_HC_TablaCampo> SS_HC_TablaCampo { get; set; }
    }
    
}
