//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Medicamento
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public string Linea { get; set; }
        public string Familia { get; set; }
        public string SubFamilia { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> IdUnidadTiempo { get; set; }
        public string CodigoMedicamento { get; set; }
        public Nullable<decimal> CantidadDespachada { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string Presentacion { get; set; }
        public string Dosis { get; set; }
        public Nullable<int> Tiempo { get; set; }
    
        public virtual SS_HC_UnidadMedida SS_HC_UnidadMedida { get; set; }
        public virtual SS_HC_UnidadMedida SS_HC_UnidadMedida1 { get; set; }
    }
    
}
