//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class SS_HC_Imagen
    {
        public string UnidadReplicacion { get; set; }
        public long EpisodioAtencionId { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public string Hallazgo { get; set; }
        public Nullable<System.DateTime> FechaProcedimiento { get; set; }
    
        public virtual SS_HC_Procedimiento SS_HC_Procedimiento { get; set; }
    }
    
}
