//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SoluccionSalud.Entidades.Entidades
{
    public partial class UnidadesMast
    {
        public string UnidadCodigo { get; set; }
        public Nullable<int> IdUnidadMedidaHC { get; set; }
    
        public virtual SS_HC_UnidadMedida SS_HC_UnidadMedida { get; set; }
    }
    
}
