//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSaludMVC.HceService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HceService.SoaServiceSoap")]
    public interface SoaServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaReporteOA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppSaludMVC.HceService.Formulario[] ConsultaReporteOA(string Unidad, string IdPaciente, string CodigoOA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaReporteOA", ReplyAction="*")]
        System.Threading.Tasks.Task<AppSaludMVC.HceService.Formulario[]> ConsultaReporteOAAsync(string Unidad, string IdPaciente, string CodigoOA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterOperabilidadConsultaExterna", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InterOperabilidadConsultaExterna(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterOperabilidadConsultaExterna", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InterOperabilidadConsultaExternaAsync(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterOperabilidadSalida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InterOperabilidadSalida(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterOperabilidadSalida", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InterOperabilidadSalidaAsync(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoaValidaFacturacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SoaValidaFacturacion(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoaValidaFacturacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SoaValidaFacturacionAsync(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoaHistoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SoaHistoria(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoaHistoria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SoaHistoriaAsync(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Formulario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tablaField;
        
        private string accionField;
        
        private string versionField;
        
        private string tipoFormularioField;
        
        private string rutaField;
        
        private string tituloField;
        
        private string episodioClinicoField;
        
        private string episodioAtencionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tabla {
            get {
                return this.tablaField;
            }
            set {
                this.tablaField = value;
                this.RaisePropertyChanged("Tabla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("Accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TipoFormulario {
            get {
                return this.tipoFormularioField;
            }
            set {
                this.tipoFormularioField = value;
                this.RaisePropertyChanged("TipoFormulario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
                this.RaisePropertyChanged("Ruta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EpisodioClinico {
            get {
                return this.episodioClinicoField;
            }
            set {
                this.episodioClinicoField = value;
                this.RaisePropertyChanged("EpisodioClinico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EpisodioAtencion {
            get {
                return this.episodioAtencionField;
            }
            set {
                this.episodioAtencionField = value;
                this.RaisePropertyChanged("EpisodioAtencion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SS_HC_WS_EpisodioAtencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _UnidadReplicacionField;
        
        private System.Nullable<int> _IdEpisodioAtencionField;
        
        private System.Nullable<int> _IdPacienteField;
        
        private System.Nullable<int> _EpisodioClinicoField;
        
        private System.Nullable<int> _IdOrdenAtencionField;
        
        private System.Nullable<int> _LineaField;
        
        private string _SecuenciaHCEField;
        
        private string _AccionField;
        
        private string _VersionField;
        
        private System.Nullable<int> _EstadoField;
        
        private string _UsuarioCreacionField;
        
        private System.Nullable<System.DateTime> _FechaCreacionField;
        
        private string _UsuarioModificacionField;
        
        private System.Nullable<System.DateTime> _FechaModificacionField;
        
        private System.Nullable<int> idEpisodioAtencionField;
        
        private System.Nullable<int> idPacienteField;
        
        private System.Nullable<int> episodioClinicoField;
        
        private System.Nullable<int> idOrdenAtencionField;
        
        private System.Nullable<int> lineaField;
        
        private System.Nullable<int> estadoField;
        
        private string unidadReplicacionField;
        
        private string secuenciaHCEField;
        
        private string accionField;
        
        private string versionField;
        
        private string usuarioCreacionField;
        
        private System.Nullable<System.DateTime> fechaCreacionField;
        
        private string usuarioModificacionField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string _UnidadReplicacion {
            get {
                return this._UnidadReplicacionField;
            }
            set {
                this._UnidadReplicacionField = value;
                this.RaisePropertyChanged("_UnidadReplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> _IdEpisodioAtencion {
            get {
                return this._IdEpisodioAtencionField;
            }
            set {
                this._IdEpisodioAtencionField = value;
                this.RaisePropertyChanged("_IdEpisodioAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> _IdPaciente {
            get {
                return this._IdPacienteField;
            }
            set {
                this._IdPacienteField = value;
                this.RaisePropertyChanged("_IdPaciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> _EpisodioClinico {
            get {
                return this._EpisodioClinicoField;
            }
            set {
                this._EpisodioClinicoField = value;
                this.RaisePropertyChanged("_EpisodioClinico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> _IdOrdenAtencion {
            get {
                return this._IdOrdenAtencionField;
            }
            set {
                this._IdOrdenAtencionField = value;
                this.RaisePropertyChanged("_IdOrdenAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> _Linea {
            get {
                return this._LineaField;
            }
            set {
                this._LineaField = value;
                this.RaisePropertyChanged("_Linea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string _SecuenciaHCE {
            get {
                return this._SecuenciaHCEField;
            }
            set {
                this._SecuenciaHCEField = value;
                this.RaisePropertyChanged("_SecuenciaHCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string _Accion {
            get {
                return this._AccionField;
            }
            set {
                this._AccionField = value;
                this.RaisePropertyChanged("_Accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string _Version {
            get {
                return this._VersionField;
            }
            set {
                this._VersionField = value;
                this.RaisePropertyChanged("_Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> _Estado {
            get {
                return this._EstadoField;
            }
            set {
                this._EstadoField = value;
                this.RaisePropertyChanged("_Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string _UsuarioCreacion {
            get {
                return this._UsuarioCreacionField;
            }
            set {
                this._UsuarioCreacionField = value;
                this.RaisePropertyChanged("_UsuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> _FechaCreacion {
            get {
                return this._FechaCreacionField;
            }
            set {
                this._FechaCreacionField = value;
                this.RaisePropertyChanged("_FechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string _UsuarioModificacion {
            get {
                return this._UsuarioModificacionField;
            }
            set {
                this._UsuarioModificacionField = value;
                this.RaisePropertyChanged("_UsuarioModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> _FechaModificacion {
            get {
                return this._FechaModificacionField;
            }
            set {
                this._FechaModificacionField = value;
                this.RaisePropertyChanged("_FechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> IdEpisodioAtencion {
            get {
                return this.idEpisodioAtencionField;
            }
            set {
                this.idEpisodioAtencionField = value;
                this.RaisePropertyChanged("IdEpisodioAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> IdPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
                this.RaisePropertyChanged("IdPaciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> EpisodioClinico {
            get {
                return this.episodioClinicoField;
            }
            set {
                this.episodioClinicoField = value;
                this.RaisePropertyChanged("EpisodioClinico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> IdOrdenAtencion {
            get {
                return this.idOrdenAtencionField;
            }
            set {
                this.idOrdenAtencionField = value;
                this.RaisePropertyChanged("IdOrdenAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
                this.RaisePropertyChanged("Linea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string UnidadReplicacion {
            get {
                return this.unidadReplicacionField;
            }
            set {
                this.unidadReplicacionField = value;
                this.RaisePropertyChanged("UnidadReplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string SecuenciaHCE {
            get {
                return this.secuenciaHCEField;
            }
            set {
                this.secuenciaHCEField = value;
                this.RaisePropertyChanged("SecuenciaHCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("Accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UsuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("UsuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("UsuarioModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("FechaModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoaServiceSoapChannel : AppSaludMVC.HceService.SoaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoaServiceSoapClient : System.ServiceModel.ClientBase<AppSaludMVC.HceService.SoaServiceSoap>, AppSaludMVC.HceService.SoaServiceSoap {
        
        public SoaServiceSoapClient() {
        }
        
        public SoaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppSaludMVC.HceService.Formulario[] ConsultaReporteOA(string Unidad, string IdPaciente, string CodigoOA) {
            return base.Channel.ConsultaReporteOA(Unidad, IdPaciente, CodigoOA);
        }
        
        public System.Threading.Tasks.Task<AppSaludMVC.HceService.Formulario[]> ConsultaReporteOAAsync(string Unidad, string IdPaciente, string CodigoOA) {
            return base.Channel.ConsultaReporteOAAsync(Unidad, IdPaciente, CodigoOA);
        }
        
        public int InterOperabilidadConsultaExterna(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico) {
            return base.Channel.InterOperabilidadConsultaExterna(UnidadReplicacion, IdEpisodioAtencion, IdPaciente, EpisodioClinico);
        }
        
        public System.Threading.Tasks.Task<int> InterOperabilidadConsultaExternaAsync(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico) {
            return base.Channel.InterOperabilidadConsultaExternaAsync(UnidadReplicacion, IdEpisodioAtencion, IdPaciente, EpisodioClinico);
        }
        
        public int InterOperabilidadSalida(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico) {
            return base.Channel.InterOperabilidadSalida(UnidadReplicacion, IdEpisodioAtencion, IdPaciente, EpisodioClinico);
        }
        
        public System.Threading.Tasks.Task<int> InterOperabilidadSalidaAsync(string UnidadReplicacion, int IdEpisodioAtencion, int IdPaciente, int EpisodioClinico) {
            return base.Channel.InterOperabilidadSalidaAsync(UnidadReplicacion, IdEpisodioAtencion, IdPaciente, EpisodioClinico);
        }
        
        public System.Data.DataTable SoaValidaFacturacion(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion) {
            return base.Channel.SoaValidaFacturacion(Id, SS_HC_WS_EpisodioAtencion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SoaValidaFacturacionAsync(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion) {
            return base.Channel.SoaValidaFacturacionAsync(Id, SS_HC_WS_EpisodioAtencion);
        }
        
        public string SoaHistoria(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion) {
            return base.Channel.SoaHistoria(Id, SS_HC_WS_EpisodioAtencion);
        }
        
        public System.Threading.Tasks.Task<string> SoaHistoriaAsync(int Id, AppSaludMVC.HceService.SS_HC_WS_EpisodioAtencion SS_HC_WS_EpisodioAtencion) {
            return base.Channel.SoaHistoriaAsync(Id, SS_HC_WS_EpisodioAtencion);
        }
    }
}
