//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APLICACIONESMAST
    {
        public APLICACIONESMAST()
        {
            this.ParametrosMasts = new HashSet<ParametrosMast>();
        }
    
        public string APLICACIONCODIGO { get; set; }
        public string DESCRIPCIONCORTA { get; set; }
        public string DESCRIPCIONLARGA { get; set; }
        public string ULTIMOPERIODOCONTABLE { get; set; }
        public string SISTEMAFUENTE { get; set; }
        public string ESTADISPONIBLE { get; set; }
        public string DEPARTAMENTOREVISOR { get; set; }
        public string ULTIMOPERIODOPROCESADO { get; set; }
        public string APLICACIONUSUARIO { get; set; }
        public string APLICACIONUSUARIO02 { get; set; }
        public string APLICACIONUSUARIO03 { get; set; }
        public string APLICACIONUSUARIO04 { get; set; }
        public string ESTADO { get; set; }
        public string ULTIMOUSUARIO { get; set; }
        public Nullable<System.DateTime> ULTIMAFECHAMODIF { get; set; }
        public string ACCION { get; set; }
    
        public virtual ICollection<ParametrosMast> ParametrosMasts { get; set; }
    }
}
