//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_CO_ComponenteGrupoCaracteristica
    {
        public CM_CO_ComponenteGrupoCaracteristica()
        {
            this.CM_CO_Componente = new HashSet<CM_CO_Componente>();
            this.CM_CO_ComponenteGrupoCaracteristica1 = new HashSet<CM_CO_ComponenteGrupoCaracteristica>();
        }
    
        public int IdGrupoComponente { get; set; }
        public Nullable<int> IdGrupoComponentePadre { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Nivel { get; set; }
    
        public virtual ICollection<CM_CO_Componente> CM_CO_Componente { get; set; }
        public virtual ICollection<CM_CO_ComponenteGrupoCaracteristica> CM_CO_ComponenteGrupoCaracteristica1 { get; set; }
        public virtual CM_CO_ComponenteGrupoCaracteristica CM_CO_ComponenteGrupoCaracteristica2 { get; set; }
    }
}
