//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_CO_ClasificacionComponente
    {
        public CM_CO_ClasificacionComponente()
        {
            this.CM_CO_Componente = new HashSet<CM_CO_Componente>();
            this.CM_CO_ClasificacionComponente1 = new HashSet<CM_CO_ClasificacionComponente>();
        }
    
        public int IdClasificacion { get; set; }
        public Nullable<int> IdClasificacionPadre { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string CadenaRecursividad { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string CuentaVentaComercial { get; set; }
        public string CuentaDescuentoVentaComercial { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<CM_CO_Componente> CM_CO_Componente { get; set; }
        public virtual ICollection<CM_CO_ClasificacionComponente> CM_CO_ClasificacionComponente1 { get; set; }
        public virtual CM_CO_ClasificacionComponente CM_CO_ClasificacionComponente2 { get; set; }
    }
}
