//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOMAST
    {
        public int Empleado { get; set; }
        public string TipoPago { get; set; }
        public string TipoTrabajador { get; set; }
        public string Raza { get; set; }
        public string Religion { get; set; }
        public string TipoVisa { get; set; }
        public Nullable<System.DateTime> VisaFechaInicio { get; set; }
        public Nullable<System.DateTime> VisaFechaExpiracion { get; set; }
        public Nullable<System.DateTime> ServicioMilitarDesde { get; set; }
        public Nullable<System.DateTime> ServicioMilitarHasta { get; set; }
        public string NumeroArchivo { get; set; }
        public string UnidadNegocioAsignada { get; set; }
        public string LocacionAsignada { get; set; }
        public string LocaciondePago { get; set; }
        public string ResponsableEmpleado { get; set; }
        public string ResponsableJefe { get; set; }
        public string ResponsableSueldo { get; set; }
        public string CodigoUsuario { get; set; }
        public string TipoAsistenciaSocial { get; set; }
        public string CentroAsistenciaSocial { get; set; }
        public string TipoCarnetAsistenciaSocial { get; set; }
        public string CarnetAsistenciaSocial { get; set; }
        public string TipoPension { get; set; }
        public Nullable<System.DateTime> FechaInicioPension { get; set; }
        public Nullable<System.DateTime> FechaTerminoPension { get; set; }
        public string CodigoAFP { get; set; }
        public string NumeroAFP { get; set; }
        public string BancoCTS { get; set; }
        public string TipoCuentaCTS { get; set; }
        public string TipoMonedaCTS { get; set; }
        public string NumeroCuentaCTS { get; set; }
        public string EstadoEmpleado { get; set; }
        public string TipoPlanilla { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaUltimaPlanilla { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaInicioContrato { get; set; }
        public Nullable<System.DateTime> FechaFinContrato { get; set; }
        public Nullable<System.DateTime> FechaCese { get; set; }
        public string RazonCese { get; set; }
        public Nullable<int> Contratista { get; set; }
        public string CompaniaSocio { get; set; }
        public string CentroCostos { get; set; }
        public string AFE { get; set; }
        public string DeptoOrganizacion { get; set; }
        public Nullable<int> TipoHorario { get; set; }
        public string GradoSalario { get; set; }
        public string Cargo { get; set; }
        public string Posicion { get; set; }
        public string NivelAcceso { get; set; }
        public string FlagIPSSVIDA { get; set; }
        public string FlagAccTrabajo { get; set; }
        public string FlagSindicato { get; set; }
        public string FlagCooperativa { get; set; }
        public string FlagRetencionJudicial { get; set; }
        public string FlagReingresos { get; set; }
        public string FlagComision { get; set; }
        public string FlagImpuestoRenta { get; set; }
        public string CorreoInterno { get; set; }
        public Nullable<decimal> SueldoActualLocal { get; set; }
        public Nullable<decimal> SueldoActualDolar { get; set; }
        public Nullable<decimal> SueldoAnteriorLocal { get; set; }
        public Nullable<decimal> SueldoAnteriorDolar { get; set; }
        public string MonedaPago { get; set; }
        public Nullable<int> EmpleadoRelacionado { get; set; }
        public string Foto { get; set; }
        public string TarjetadeCredito { get; set; }
        public Nullable<int> MotivoCese { get; set; }
        public string DepartamentoOrganizacional { get; set; }
        public string DepartamentoOperacional { get; set; }
        public Nullable<int> Perfil { get; set; }
        public string NivelSalario { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaReingreso { get; set; }
        public string UnidadReplicacion { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
        public Nullable<System.DateTime> UltimaFechaPagoVacacion { get; set; }
        public Nullable<int> Gerencia { get; set; }
        public Nullable<int> SubGerencia { get; set; }
        public Nullable<double> RedondeoACuenta { get; set; }
        public string RUCCentroAsistenciaSocial { get; set; }
        public Nullable<int> PlantillaConcepto { get; set; }
        public string Sucursal { get; set; }
        public string Actividad { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string EstadoNivelacion { get; set; }
        public Nullable<int> AprobadorNivelacion { get; set; }
        public Nullable<int> SolicitadorNivelacion { get; set; }
        public string FlagSMF { get; set; }
        public Nullable<System.DateTime> FechaVacaciones { get; set; }
        public string Formato_2 { get; set; }
        public Nullable<decimal> GrupoOcupacional { get; set; }
        public Nullable<int> PosicionOrganigrama { get; set; }
        public string FlagAccTrabajoP { get; set; }
        public string sucursalbanconacion { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> ClienteUnidad { get; set; }
        public Nullable<int> TareoNivel { get; set; }
        public Nullable<int> EmpleadoNivel { get; set; }
        public Nullable<decimal> TipoPuesto { get; set; }
        public string telefonoextranjero { get; set; }
        public string celularextranjero { get; set; }
        public string celularemergencia { get; set; }
        public string telefonoemergencia { get; set; }
        public string FirmaDigitalizada { get; set; }
        public string FlagJefeDepartamento { get; set; }
        public string FlagPorcentaje { get; set; }
        public string Planta { get; set; }
        public string provincia { get; set; }
        public string ClasificadorMovimiento { get; set; }
        public string ConceptoGasto { get; set; }
        public string UnidadOrganizacional { get; set; }
        public string CentroCosto_ABU { get; set; }
        public Nullable<int> IdEjecutivo { get; set; }
        public Nullable<int> JefeResponsable { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public string Almacen { get; set; }
        public string CMP { get; set; }
        public Nullable<int> idTipoAtencion { get; set; }
        public Nullable<int> idGrupoAtencion { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
        public string FlagTrabajadorPensionista { get; set; }
        public string FlagSCTRSalud { get; set; }
        public string FlagSCTRPension { get; set; }
        public string FlagDiscapacidad { get; set; }
        public string FlagSujetoControl { get; set; }
        public string FlagSindicalizado { get; set; }
        public string FlagDomiciliado { get; set; }
        public string NivelEducativoRTPS { get; set; }
        public string flagregimenalternativo { get; set; }
        public string flagjornadamaxima { get; set; }
        public string flaghorarionocturno { get; set; }
        public string flagotrosquinta { get; set; }
        public string flagquintaexonerada { get; set; }
        public string situacionespecial { get; set; }
        public string flagmadreresponsabilidad { get; set; }
        public string flagcentroformacion { get; set; }
        public string tipomodalidadformativa { get; set; }
        public string PrestadorServicio { get; set; }
        public Nullable<int> IndicadorImpRenta { get; set; }
        public Nullable<int> IndicadorTarjetaCredito { get; set; }
        public Nullable<int> TipoMedico { get; set; }
        public Nullable<int> Pool { get; set; }
        public string ClaveFirmaDigital { get; set; }
        public string FirmaDigital { get; set; }
        public string FlagAseguraPension { get; set; }
        public string CategoriaOcupacional { get; set; }
        public string FlagConvenioDobleTrib { get; set; }
        public string FlagDeConfianza { get; set; }
        public string EstablecimientoRTPS { get; set; }
        public Nullable<System.DateTime> FechaBajaEPS { get; set; }
        public Nullable<int> EmpleadoRepresentante { get; set; }
        public string TipoActividad { get; set; }
        public Nullable<int> CodigoUnidad { get; set; }
        public string area_tmp { get; set; }
        public string cargo_tmp { get; set; }
        public string TipoTrabajadorSalud { get; set; }
        public Nullable<int> IndSupervisorLiquidacion { get; set; }
        public string Division { get; set; }
        public Nullable<int> IndicadorImpPDF { get; set; }
        public string RutaImpPDF { get; set; }
        public string RutaCurriculum { get; set; }
        public string TipoComisionAFP { get; set; }
        public string ACCION { get; set; }
    
        public virtual PERSONAMAST PERSONAMAST { get; set; }
    }
}
