//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Varios
    {
        public GE_Varios()
        {
            this.GE_Varios1 = new HashSet<GE_Varios>();
        }
    
        public string CodigoTabla { get; set; }
        public int Secuencial { get; set; }
        public string CodigoTablaPadre { get; set; }
        public Nullable<int> SecuencialPadre { get; set; }
        public string Nemonico { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public string ValorTexto { get; set; }
        public Nullable<int> IndicadorUso { get; set; }
        public Nullable<int> IndicadorAgregarHijo { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> OrdenEstablecido { get; set; }
        public string Accion { get; set; }
    
        public virtual ICollection<GE_Varios> GE_Varios1 { get; set; }
        public virtual GE_Varios GE_Varios2 { get; set; }
    }
}
