//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_FlujoProceso
    {
        public int MacroProceso { get; set; }
        public string Proceso { get; set; }
        public Nullable<int> Orden { get; set; }
        public string ConceptoSeguridad { get; set; }
    
        public virtual HC_Proceso HC_Proceso { get; set; }
    }
}
