//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_Proceso
    {
        public HC_Proceso()
        {
            this.HC_FlujoProceso = new HashSet<HC_FlujoProceso>();
            this.HC_SubProceso = new HashSet<HC_SubProceso>();
        }
    
        public string Proceso { get; set; }
        public string TipoProceso { get; set; }
        public string Descripcion { get; set; }
        public string Icono { get; set; }
    
        public virtual ICollection<HC_FlujoProceso> HC_FlujoProceso { get; set; }
        public virtual ICollection<HC_SubProceso> HC_SubProceso { get; set; }
    }
}
