//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MiscelaneosHeader
    {
        public MA_MiscelaneosHeader()
        {
            this.MA_MiscelaneosDetalle = new HashSet<MA_MiscelaneosDetalle>();
        }
    
        public string AplicacionCodigo { get; set; }
        public string CodigoTabla { get; set; }
        public string Compania { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionExtranjera { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public byte[] Timestamp { get; set; }
        public string ACCION { get; set; }
    
        public virtual ICollection<MA_MiscelaneosDetalle> MA_MiscelaneosDetalle { get; set; }
    }
}
