//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURIDADAUTORIZACIONE
    {
        public string APLICACIONCODIGO { get; set; }
        public string GRUPO { get; set; }
        public string CONCEPTO { get; set; }
        public string USUARIO { get; set; }
        public string OPCIONAGREGARFLAG { get; set; }
        public string OPCIONMODIFICARFLAG { get; set; }
        public string OPCIONBORRARFLAG { get; set; }
        public string OPCIONAPROBARFLAG { get; set; }
        public string ESTADO { get; set; }
        public string ULTIMOUSUARIO { get; set; }
        public Nullable<System.DateTime> ULTIMAFECHAMODIF { get; set; }
        public string ACCION { get; set; }
    
        public virtual SEGURIDADGRUPO SEGURIDADGRUPO { get; set; }
        public virtual SEGURIDADGRUPO SEGURIDADGRUPO1 { get; set; }
    }
}
