//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_AgenteOpcion
    {
        public int IdAgente { get; set; }
        public int IdOpcion { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public string ValorTexto { get; set; }
        public Nullable<int> IndicadorAcceso { get; set; }
        public Nullable<int> IndicadorHabilitado { get; set; }
        public Nullable<int> IndicadorObligatorio { get; set; }
        public Nullable<int> IndicadorVisible { get; set; }
        public Nullable<int> IndicadorPrioridad { get; set; }
        public Nullable<int> IndicadorNuevo { get; set; }
        public Nullable<int> IndicadorModificar { get; set; }
        public Nullable<int> IndicadorEliminar { get; set; }
        public Nullable<int> IndicadorImprimir { get; set; }
        public Nullable<int> IndicadorIngreso { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
    
        public virtual SG_Agente SG_Agente { get; set; }
        public virtual SG_Opcion SG_Opcion { get; set; }
    }
}
