//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_AD_OrdenAtencionDetalle
    {
        public int IdOrdenAtencion { get; set; }
        public int Linea { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> Especialidad { get; set; }
        public Nullable<int> IdCita { get; set; }
        public Nullable<int> IndicadorCobrado { get; set; }
        public Nullable<int> IndicadorDisponible { get; set; }
        public Nullable<int> IndicadorProcedimiento { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string TipoComponente { get; set; }
        public string Componente { get; set; }
        public string SubFamilia { get; set; }
        public string Familia { get; set; }
        public string LineaFamilia { get; set; }
        public string LoteComponente { get; set; }
        public string CondicionComponente { get; set; }
        public string ProcedenciaComponente { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> CantidadPresupuestada { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadDespachada { get; set; }
        public Nullable<decimal> CantidadDevuelta { get; set; }
        public Nullable<int> PeriodoEmision { get; set; }
        public Nullable<int> IdEstablecimiento { get; set; }
        public string Compania { get; set; }
        public string Sucursal { get; set; }
        public string CentroCosto { get; set; }
        public string ClasificadorMovimiento { get; set; }
        public string UnidadOrganizacional { get; set; }
        public string Proyecto { get; set; }
        public string ConceptoGasto { get; set; }
        public Nullable<int> IdOPC { get; set; }
        public string TipoOPC { get; set; }
        public string SerieOPC { get; set; }
        public Nullable<int> NumeroOPC { get; set; }
        public string TipoRelacion { get; set; }
        public Nullable<int> IdDocumentoRelacionado { get; set; }
        public string TipoDocumentoRelacionado { get; set; }
        public string SerieDocumentoRelacionado { get; set; }
        public string DocumentoRelacionado { get; set; }
        public Nullable<int> LineaDocumentoRelacionado { get; set; }
        public string CampoReferencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IndicadorCoberturado { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IndicadorTransferir { get; set; }
        public Nullable<int> IndicadorReceta { get; set; }
        public Nullable<int> IndicadorExpediente { get; set; }
        public Nullable<int> NumeroExpediente { get; set; }
        public Nullable<int> IndicadorFacturacion { get; set; }
        public Nullable<int> IdProcesoExpediente { get; set; }
        public Nullable<System.DateTime> FechaProcesoExpediente { get; set; }
        public Nullable<int> IndicadorEPS { get; set; }
        public string UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<decimal> CantidadSuministrada { get; set; }
        public Nullable<decimal> CantidadRecepcionada { get; set; }
        public string AlmacenDestino { get; set; }
        public Nullable<int> IndicadorSeCobra { get; set; }
        public string Especimen { get; set; }
        public string EnfermedadActual { get; set; }
        public string Hallazgos_Operatorios { get; set; }
        public string Diagnostico_Clinico { get; set; }
        public Nullable<int> TipoTecnica { get; set; }
        public Nullable<decimal> FactorConversion { get; set; }
        public string MotivoRechazo { get; set; }
        public Nullable<int> SecuencialDocumentoRelacionado { get; set; }
        public Nullable<int> TipoReceta { get; set; }
        public Nullable<decimal> CantidadDesechada { get; set; }
        public Nullable<int> Situacion { get; set; }
        public Nullable<int> SituacionInterfase { get; set; }
        public Nullable<int> GrupoInterfase { get; set; }
        public Nullable<int> SecuencialInterfase { get; set; }
        public Nullable<int> IdTransaccionCambioHospitalizacion { get; set; }
        public Nullable<int> tipoordenatencion_bk { get; set; }
        public Nullable<int> IdPersonaAntUnificacion { get; set; }
        public Nullable<int> IndicadorCorreoLaboratorio { get; set; }
        public Nullable<int> MotivoInterFase { get; set; }
        public Nullable<int> IndicadorAlertaInterfase { get; set; }
        public Nullable<System.DateTime> FechaAlertaInterfase { get; set; }
        public Nullable<int> IndicadorExpedienteBk { get; set; }
        public Nullable<int> NumeroExpedienteBk { get; set; }
        public Nullable<int> IdProcesoExpedienteBk { get; set; }
        public Nullable<int> IndicadorHonorarios { get; set; }
        public Nullable<int> IndicadorPlanilla { get; set; }
        public Nullable<int> IndicadorCostoCero { get; set; }
        public Nullable<int> TipoInterConsulta { get; set; }
        public Nullable<int> IndicadorOcultarConsulta { get; set; }
        public Nullable<int> IndicadorReingresoSalida { get; set; }
        public Nullable<System.DateTime> FechaAplicacion { get; set; }
        public Nullable<int> IndicadorEliminado { get; set; }
        public Nullable<int> IndicadorValidarFechaTrat { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public Nullable<int> Cuarto { get; set; }
        public Nullable<int> Cama { get; set; }
        public Nullable<int> ModoIngreso { get; set; }
        public Nullable<int> IndRequiereCirugia { get; set; }
        public Nullable<int> IdDiagnostico { get; set; }
        public string ComponentePaquete { get; set; }
        public Nullable<int> IndicadorPaquete { get; set; }
        public Nullable<int> IndicadorRiesgoQuirurgico { get; set; }
        public string ObservacionHospitalizacion { get; set; }
        public Nullable<int> TipoHospitalizacion { get; set; }
        public Nullable<int> IdOAOrigenTraslado { get; set; }
        public Nullable<int> IndicadorLlegada { get; set; }
        public Nullable<int> SituacionLineaHosp { get; set; }
        public Nullable<int> IndicadorAgregado { get; set; }
        public Nullable<int> IndicadorMigradoHospital { get; set; }
        public Nullable<int> LineaHospInicial { get; set; }
        public Nullable<int> SituacionLineaHospPreAltaAdm { get; set; }
        public Nullable<int> IndicadorEstHospIngresoLinea { get; set; }
        public Nullable<int> IdVisita { get; set; }
        public Nullable<int> OrdenPerfil { get; set; }
        public Nullable<int> IndicadorPerfil { get; set; }
        public string ComponentePerfil { get; set; }
    
        public virtual SS_AD_OrdenAtencion SS_AD_OrdenAtencion { get; set; }
        public virtual SS_GE_Paciente SS_GE_Paciente { get; set; }
    }
}
