//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_GE_Paciente
    {
        public SS_GE_Paciente()
        {
            this.SS_AD_OrdenAtencion = new HashSet<SS_AD_OrdenAtencion>();
            this.SS_AD_OrdenAtencionDetalle = new HashSet<SS_AD_OrdenAtencionDetalle>();
            this.SS_HC_EpisodioClinico = new HashSet<SS_HC_EpisodioClinico>();
        }
    
        public int IdPaciente { get; set; }
        public Nullable<int> TipoPaciente { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Raza { get; set; }
        public string Religion { get; set; }
        public string Cargo { get; set; }
        public string AreaLaboral { get; set; }
        public string Ocupacion { get; set; }
        public string CodigoHC { get; set; }
        public string CodigoHCAnterior { get; set; }
        public string CodigoHCSecundario { get; set; }
        public string TipoAlmacenamiento { get; set; }
        public string TipoHistoria { get; set; }
        public string TipoSituacion { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public string LugarProcedencia { get; set; }
        public string RutaFoto { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IndicadorNuevo { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> NumeroFile { get; set; }
        public string Servicio { get; set; }
        public string UsuarioAlmacenamiento { get; set; }
        public Nullable<System.DateTime> FechaAlmacenamiento { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IndicadorAsistencia { get; set; }
        public Nullable<int> CantidadAsistencia { get; set; }
        public Nullable<int> UbicacionHHCC { get; set; }
        public Nullable<int> IndicadorMigradoSiteds { get; set; }
        public string NumeroCaja { get; set; }
        public Nullable<int> IndicadorCodigoBarras { get; set; }
        public Nullable<int> IDPACIENTE_OK { get; set; }
        public string CodigoAsegurado { get; set; }
        public Nullable<int> NumeroPoliza { get; set; }
        public Nullable<int> NumeroCertificado { get; set; }
        public string CodigoProducto { get; set; }
        public string CodigoPlan { get; set; }
        public Nullable<int> TipoParentesco { get; set; }
        public string CodigoBeneficio { get; set; }
        public Nullable<int> Situacion { get; set; }
        public Nullable<int> TomoActual { get; set; }
        public Nullable<int> IndicadorHistoriaFisica { get; set; }
        public string DescripcionHistoria { get; set; }
        public string Accion { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public string AtencionLugar { get; set; }
        public string Atencion { get; set; }
        public string IdEstablecimientoIngreso { get; set; }
        public string IdServicioIngreso { get; set; }
        public string Prestacion { get; set; }
        public string Destino { get; set; }
        public Nullable<int> NroAutorizacion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaIngresoHosp { get; set; }
        public Nullable<System.DateTime> FechaCorteHosp { get; set; }
        public string Establecimiento01 { get; set; }
        public string ReferenciaHoja01 { get; set; }
        public string Establecimiento02 { get; set; }
        public string ReferenciaHoja02 { get; set; }
    
        public virtual ICollection<SS_AD_OrdenAtencion> SS_AD_OrdenAtencion { get; set; }
        public virtual ICollection<SS_AD_OrdenAtencionDetalle> SS_AD_OrdenAtencionDetalle { get; set; }
        public virtual ICollection<SS_HC_EpisodioClinico> SS_HC_EpisodioClinico { get; set; }
    }
}
