//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_ProcedimientoPrueba
    {
        public int IdProcedimiento { get; set; }
        public int IdPrueba { get; set; }
        public string CodigoPrueba { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual SS_HC_UnidadMedida SS_HC_UnidadMedida { get; set; }
    }
}
