//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_ProcedimientoEjecucion
    {
        public SS_HC_ProcedimientoEjecucion()
        {
            this.SS_HC_ProcedimientoInforme = new HashSet<SS_HC_ProcedimientoInforme>();
        }
    
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public int Secuencia { get; set; }
        public string UnidadReplicacionSolicitado { get; set; }
        public Nullable<long> IdEpisodioAtencionSolicitado { get; set; }
        public Nullable<int> IdPacienteSolicitado { get; set; }
        public Nullable<int> EpisodioClinicoSolicitado { get; set; }
        public Nullable<int> SecuenciaSolicitado { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public string CodigoComponente { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaProcedimiento { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaInforme { get; set; }
        public Nullable<int> IndicadorPreparacion { get; set; }
        public Nullable<int> IndicadorAutorizacion { get; set; }
        public Nullable<int> Medico { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TipoAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdMedicoAutoriza { get; set; }
        public string ObservacionAlta { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ACCION { get; set; }
        public string TipoCodigo { get; set; }
    
        public virtual ICollection<SS_HC_ProcedimientoInforme> SS_HC_ProcedimientoInforme { get; set; }
    }
}
