//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_EpisodioAtencion
    {
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<long> EpisodioAtencion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public string UnidadReplicacionEC { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public string TipoTrabajador { get; set; }
        public string TipoEpisodio { get; set; }
        public string IdEpisodioAtencionCodigo { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string ProximaAtencionFlag { get; set; }
        public Nullable<int> IdEspecialidadProxima { get; set; }
        public Nullable<int> IdEstablecimientoSaludProxima { get; set; }
        public Nullable<int> IdTipoInterConsulta { get; set; }
        public Nullable<int> IdTipoReferencia { get; set; }
        public string ObservacionProxima { get; set; }
        public string DescansoMedico { get; set; }
        public Nullable<int> DiasDescansoMedico { get; set; }
        public Nullable<System.DateTime> FechaInicioDescansoMedico { get; set; }
        public Nullable<System.DateTime> FechaFinDescansoMedico { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public string ObservacionOrden { get; set; }
        public Nullable<int> IdTipoOrden { get; set; }
        public Nullable<int> FlagFirma { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public Nullable<int> idMedicoFirma { get; set; }
        public string ObservacionFirma { get; set; }
        public string KeyPrivada { get; set; }
        public string KeyPublica { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string TipoUbicacion { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> FlagCierrePorRegla { get; set; }
    
        public virtual SS_HC_EpisodioAtencionMaster SS_HC_EpisodioAtencionMaster { get; set; }
        public virtual SS_HC_Procedimiento SS_HC_Procedimiento { get; set; }
        public virtual SS_HC_EpisodioClinico SS_HC_EpisodioClinico { get; set; }
        public virtual SS_HC_EstablecimientoSalud SS_HC_EstablecimientoSalud { get; set; }
        public virtual SS_HC_PersonalSalud SS_HC_PersonalSalud { get; set; }
    }
}
