//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_AuditRoyal
    {
        public long AuditID { get; set; }
        public string HostName { get; set; }
        public string Aplicacion { get; set; }
        public string Modulo { get; set; }
        public string Usuario { get; set; }
        public string Type { get; set; }
        public string TableName { get; set; }
        public Nullable<long> TableIdValue { get; set; }
        public string PrimaryKeyData { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VistaData { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> Version { get; set; }
    }
}
