//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_AnatomiaPatologica
    {
        public string UnidadReplicacion { get; set; }
        public long EpisodioAtencionId { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdProcedimiento { get; set; }
        public string Hallazgo { get; set; }
        public Nullable<System.DateTime> FechaProcedimiento { get; set; }
    }
}
