//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EpisodioAtenciones
    {
        public int Persona { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string NombreCompleto { get; set; }
        public string UnidadReplicacion { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<long> Episodio_Atencion { get; set; }
        public Nullable<System.DateTime> FechaReg_EpisoAtencon { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> Estado_EpisodioAten { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string MotivoConsulta { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Accion { get; set; }
        public int EpisodioClinico { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public string UnidadReplicacionEC { get; set; }
        public Nullable<int> IdEstablecimientoSalud { get; set; }
        public Nullable<int> IdUnidadServicio { get; set; }
        public Nullable<int> IdPersonalSalud { get; set; }
        public string PersonalSaludNombre { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string especialidadNombre { get; set; }
        public Nullable<int> CodigoEpisodioClinico { get; set; }
        public string IdEpisodioAtencionCodigo { get; set; }
        public string CodigoOA { get; set; }
        public string TipoTrabajador { get; set; }
        public string TipoTrabajador_Desc { get; set; }
        public Nullable<int> Id001 { get; set; }
        public int Id002 { get; set; }
        public string Codigo001 { get; set; }
        public string Codigo002 { get; set; }
        public string Codigo003 { get; set; }
        public string Codigo004 { get; set; }
        public string Descripcion001 { get; set; }
        public string Descripcion002 { get; set; }
        public string Descripcion003 { get; set; }
        public string Descripcion004 { get; set; }
        public string Documento_Paciente { get; set; }
        public string Documento_Medico { get; set; }
        public string Formato_Codigo { get; set; }
        public int Formato_Id { get; set; }
        public int Formato_Tipo { get; set; }
        public int Formato_Uso { get; set; }
        public string Formato_Descripcion { get; set; }
        public int contador_filas { get; set; }
    }
}
