//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Miscelaneos
    {
        public string AplicacionHeader { get; set; }
        public string CodigoHeader { get; set; }
        public string CompaniaHeader { get; set; }
        public string DescLocalHeader { get; set; }
        public string DescExtHeader { get; set; }
        public string EstadoHeader { get; set; }
        public string UsuarioHeader { get; set; }
        public Nullable<System.DateTime> FechaHeader { get; set; }
        public byte[] TimeHeader { get; set; }
        public string AccionHeader { get; set; }
        public string AplicacionDetalle { get; set; }
        public string CodigoDetalle { get; set; }
        public string CompaniaDetalle { get; set; }
        public string ElementoDetalle { get; set; }
        public string DescDetalle { get; set; }
        public string DescextDetalle { get; set; }
        public string ValorCodigoDetalle { get; set; }
        public string EstadoDetalle { get; set; }
        public string UsuarioDetalle { get; set; }
        public Nullable<System.DateTime> FechaDetalle { get; set; }
        public byte[] TimeDetalle { get; set; }
        public string ValorCodigo2 { get; set; }
        public string ValorCodigo3 { get; set; }
        public string ValorCodigo4 { get; set; }
        public Nullable<int> ValorEntero1 { get; set; }
        public Nullable<int> ValorEntero2 { get; set; }
        public Nullable<int> ValorEntero3 { get; set; }
        public Nullable<int> ValorEntero4 { get; set; }
    }
}
