//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_GE_ESPECIALIDADMEDICO
    {
        public int PERSONA { get; set; }
        public string ORIGEN { get; set; }
        public string NOMBRES { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string BUSQUEDA { get; set; }
        public string TIPODOCUMENTOIDENTIDAD { get; set; }
        public string DOCUMENTOIDENTIDAD { get; set; }
        public string ESCLIENTE { get; set; }
        public string ESPROVEEDOR { get; set; }
        public string ESEMPLEADO { get; set; }
        public string ESOTRO { get; set; }
        public string TIPOPERSONA { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string CIUDADNACIMIENTO { get; set; }
        public string DOCUMENTOFISCAL { get; set; }
        public string DOCUMENTO { get; set; }
        public string PERSONAANT { get; set; }
        public string CORREOELECTRONICO { get; set; }
        public string CLASEPERSONACODIGO { get; set; }
        public string ESTADO { get; set; }
        public string ULTIMOUSUARIO { get; set; }
        public Nullable<System.DateTime> ULTIMAFECHAMODIF { get; set; }
        public string TIPOPERSONAUSUARIO { get; set; }
        public string CMP { get; set; }
        public string FOTO { get; set; }
        public string NUMEROREGISTROESPECIALIDAD { get; set; }
        public Nullable<int> TIPOGENERACIONCITA { get; set; }
        public Nullable<decimal> TIEMPOPROMEDIOATENCION { get; set; }
        public Nullable<int> IDESPECIALIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string ACCION { get; set; }
        public string SEXO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public int PROGRAMADO { get; set; }
        public int SERVICIO { get; set; }
        public string TIPOHORARIO { get; set; }
        public int IDHORARIO { get; set; }
        public string CODIGOUSUARIO { get; set; }
    }
}
