//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluccionSalud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_ClaseLinea
    {
        public WH_ClaseLinea()
        {
            this.WH_ClaseFamilia = new HashSet<WH_ClaseFamilia>();
            this.WH_ClaseFamilia1 = new HashSet<WH_ClaseFamilia>();
        }
    
        public string Linea { get; set; }
        public string DescripcionLocal { get; set; }
        public string DescripcionIngles { get; set; }
        public string GrupoLinea { get; set; }
        public string ManejoColorSerieFlag { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string UltimoUsuario { get; set; }
        public string Accion { get; set; }
    
        public virtual ICollection<WH_ClaseFamilia> WH_ClaseFamilia { get; set; }
        public virtual ICollection<WH_ClaseFamilia> WH_ClaseFamilia1 { get; set; }
    }
}
